### ISSUE TITLE
Allow "*" to match scheme of protected resource

### ISSUE THREAD

**Issue by dbates-wk** [w3c/webappsec-csp#104]
We should consider expanding the definition of '\*' to match either a network scheme or the scheme of the protected resource both as a convenience to web developers and native app developers (&) and to help make the behavior of '\*' more closely conform to the natural expected behavior of a wildcard.

Brief Survey of Browser Implementations:

I created a page with the following markup and loaded it in each browser using a file URL:
```html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Security-Policy" content="img-src *">
</head>
<body>
<img src="abe.png"><!-- Downloaded from <https://trac.webkit.org/export/204030/trunk/LayoutTests/http/tests/security/resources/abe.png> -->
</body>
</html>
```

Here are the results:

| Browser | Result of loading the above page |
|----------|---------------------------------|
| Chrome Canary for Mac version 54.0.2815.0 | Image load blocked; does not show an image.|
| Firefox Nightly for Mac version 51.0a1 (2016-08-02) | Shows an image.
| Safari for Mac version Version 9.1.1 (11601.6.17) | Shows an image.
| Edge version 25.10586.0.0 (EdgeHTML version 13.10586) | Shows an image.

All browser engines show the image with the exception of Chrome. 

(&) A native app may embed a web view that loads content from a file URL (e.g. an image from its app bundle on macOS/iOS).

**Comment by shekyan** [comment]
@dbates-wk, can you please elaborate on why do you think people expect "*" to also match `data:` scheme. I am probably missing something, but `data:` was excluded since https://www.w3.org/TR/2014/WD-CSP2-20140703/ , and I personally didn't know no browser expect Chrome actually not enforcing it.

**Comment by shekyan** [comment]
BTW, both Firefox 48 and Nightly 51.0a1 (2016-08-09) for Mac block an image from `data:`:
```
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAP0AAAD9CAIAAAD4V+arAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjA76PVpAAAAC0lEQVR42gEAAP//AAAAAS4n2uEAAAAASUVORK5CYII= (“img-src *”).
```

**Comment by intchloe** [comment]
@dbates-wk 

Are you only talking about `img-src` or do you mean all resource directives? 

`data:` should be considered as dangerous so I don't see any arguments why wildcard should include that scheme. Do you mind elaborate?

**Comment by dbates-wk** [comment]
> @dbates-wk, can you please elaborate on why do you think people expect "*" to also match data: scheme. I am probably missing something, but data: was excluded since CSP 1.1, and I personally didn't know there are still browsers that do not enforce that.

Notice that the proposal is to extend the definition of * to match the scheme of the protected resource where a protected resources is defined by <http://www.w3.org/TR/CSP2/#protected-resource>. At the time of writing, the only interesting protected resource type is a Document. In the case that a Document is specified using a data URL and contains a CSP meta tag that defines a policy that contains * then I do not see the harm with allowing * to match data:.

**Comment by dbates-wk** [comment]
> @dbates-wk
> 
> Are you only talking about img-src or do you mean all resource directives?
> 

All directives.

> data: should be considered as dangerous for some directives so I don't see any arguments why wildcard should include that scheme. Do you mind elaborate?

As mentioned both in the description of this issue and in my reply to shekyan, this proposal is about extending * to match the scheme of the protected resource. Do you see an issue with allowing * to match data: for a page with a data URL? I mean, it does not seem like a security threat to allow data URL subresources embedded in a data URL to load.

**Comment by shekyan** [comment]
> Notice that the proposal is to extend the definition of * to match the scheme of the protected resource where a protected resources is defined by http://www.w3.org/TR/CSP2/#protected-resource. At the time of writing, the only interesting protected resource type is a Document. In the case that a Document is specified using a data URL and contains a CSP meta tag that defines a policy that contains * then I do not see the harm with allowing * to match data:.

It implies then, that with a policy like `default-src *` *it is not* okay to load resources from `data:` if page is loaded over `http:`, but *it is ok* if it it is loaded over `data:`. If we are trying to prevent an injection attack through `data:`, it will be prevented for the first case, but will succeed for the latter.

**Comment by dbates-wk** [comment]
> It implies then, that with a policy like default-src * it is not okay to load resources from data: if page is loaded over http:, but it is ok if it it is loaded over data:. If we are trying to prevent an injection attack through data:, it will be prevented for the first case, but will succeed for the latter.

Do you see this behavior increasing the attack surface area any more than the embedding protected resource that allows data URLs? Notice that CSP only matches data: and not the full data URL (maybe we should fix this issue by way of the HTML integrity attribute, CSP nonces, or CSP hashes?). If the embedding protected resource allows data URLs then an attacker can inject content that loads an arbitrary data URL. It is not necessary for an attacker to find a content injection vulnerability in the document encoded by a data URL that is loaded by the embedding page. A similar argument can be made for any embedded document that has the same scheme as the scheme of its embedding protected resource and would be prevented from loading if its embedding protected resource has default-src * under the current definition of *.

**Comment by shekyan** [comment]
I agree that `data:` is a special scheme and it is sad that there is no currently a way to lock down a resource loaded over `data:` to a particular payload.

Your approach doesn't give a chance to opt-out from allowing embedded resources loaded over `data:`.  But so does current approach in regards to the protected resources loaded over `http:` or `https:`, there is no way to opt-out of loading embedded resources over the same scheme if "*" was used..

I am convinced there there is probably no harm in your proposal, other than we are making things less strict for protected resources loaded over `data:` :)

**Comment by mikewest** [comment]
Skimming this quickly, I agree that it's confusing that `*` doesn't match relative URLs when loaded from a `file:` or `data:` URL. I'm not sure there's actual harm in making both `file:` and `data:` harder to use, but I don't have any real objection to changing the algorithm. If someone wants to send in a PR, I'd merge it.

**Comment by shekyan** [comment]
@dbates-wk , does https://github.com/w3c/webappsec-csp/pull/105/commits reflect your proposal properly?

**Comment by shekyan** [comment]
A protected resource loaded from non-network scheme as, say `chrome-extension:`, would automatically allow injections from potentially malicious `chrome-extension:` though, if we implement what I wrote up in #105 .

**Comment by dbates-wk** [comment]
> @dbates-wk , does #105 reflect your proposal properly?

Looks good. I noticed some minor cosmetic nits and commented on them in <https://github.com/w3c/webappsec-csp/pull/105/commits/62118b0ed44a4556aca846d479f5e49f4e6ccaf3>.

**Comment by dbates-wk** [comment]
> A protected resource loaded from non-network scheme as, say chrome-extension:, would automatically allow injections from potentially malicious extensions though, if we implement what I wrote up in #105 .

I'm not familiar with how Chrome extensions work, how CSP works with Chrome extensions, or what is the security origin/context of a Chrome extension (do they have unique origins?). I take it that the last sentence in <https://github.com/w3c/webappsec-csp/issues/104#issuecomment-239065776> does not apply for Chrome extensions?

**Comment by shekyan** [comment]
> I'm not familiar with how Chrome extensions work, how CSP works with Chrome extensions, or what is the security origin/context of a Chrome extension (do they have unique origins?). 

Extensions do have unique origins. 
>I take it that the last sentence in #104 (comment) does not apply for Chrome extensions?

Last sentence in #104 (comment) applies to network schemes only (step 1 of [6.1.13.4. Does url match expression in origin with redirect count?](https://w3c.github.io/webappsec-csp/#match-url-to-source-expression)) in the current specification. The way we wrote down the patch implies that no matter what the scheme of the protected resource is, it is going to be whitelisted if "*" is used in the source-list.

A better example of a threat introduced with the patch  is that a protected resource loaded from a `file:` with CSP specified through meta tags like `script-src *` will automatically allow requests to any scripts on the file system, which isn't a case with the current specification. 

Should we try to be as specific as possible where it is applicable (`chrome-extention:`, `file:`, even `javascript:`) and match to the exact path of the protected resource, and match scheme only for schemes like `data:` and `blob:`?

**Comment by dbates-wk** [comment]
> Last sentence in #104 (comment) applies to network schemes only (step 1 of 6.1.13.4. Does url match expression in origin with redirect count?) in the current specification.

Then I do not see the harm by the same argument as in <https://github.com/w3c/webappsec-csp/issues/104#issuecomment-239065776>.

> The way we wrote down the patch implies that no matter what the scheme of the protected resource is, it is going to be whitelisted if "*" is used in the source-list.
> 

Yes, this is the intention of the proposal and will allow subresources with relative URLs to load on a pages that has * in the appropriate source list.

> A better example of a threat introduced with the patch is that a protected resource loaded from a file: with CSP specified through meta tags like script-src * will automatically allow requests to any scripts on the file system, which isn't a case with the current specification.
> 

The argument in <https://github.com/w3c/webappsec-csp/issues/104#issuecomment-239065776> applies to this case; => I do not see how we are increasing the attack surface anymore than it would be increased as a result of a web author that wants to allow loading of scripts from changing their policy from "script-src *" to "script-src * file:" in the example.

> Should we try to be as specific as possible where it is applicable (chrome-extention:, file:, even javascript:) and match to the exact path of the protected resource, and match scheme only for schemes like data: and blob:?

I think it would be beneficial for the spec. to support exact matching for non-HTTP/HTTPS schemes so as to support usage of CSP in contexts that mix both network and non-network content (as is the case in native apps that embed a web view). I do not feel that we should address this issue in this bug as such enhancements seem disjoint to the behavior of *.

**Comment by shekyan** [comment]
> The argument in #104 (comment) applies to this case; => I do not see how we are increasing the attack surface anymore than it would be increased as a result of a web author that wants to allow loading of scripts from changing their policy from "script-src *" to "script-src * file:" in the example.

I agree that we do not increase the attack surface, formally. Experienced author would put `script-src * file:/specific/path/he/wants/to/whitelist/`, and he still can do that with our patch, as intersection of `file:` and `file:/whatever` produces `file:/whatever`. Inexperienced author might not realize that by using `script-src *` he will whitelist the whole `file:` scheme. I'll work on detailed note describing the consequences of the change then.

**Comment by mikewest** [comment]
> Should we try to be as specific as possible where it is applicable (chrome-extention:, file:, even javascript:) and match to the exact path of the protected resource, and match scheme only for schemes like data: and blob:?

1. It's not clear to me what we'd gain by doing so.
2. CSP doesn't seem like the place to make this kind of decision about the security properties of a given scheme. We defer to HTML, et al. for `origin` and `origin of a url`. I'd like to continue working at that level of abstraction in this document.

>  Experienced author would put script-src * file:/specific/path/he/wants/to/whitelist/, and he still can do that with our patch, as intersection of file: and file:/whatever produces file:/whatever

That's not the case. That is, `script-src * https://whatever` is the same as `script-src *` (as each item adds to the whitelist). The developer would not be able to use `*` while at the same time restricting what `*` means. This seems like a fairly minimal risk, honestly, as `*` is already fairly wildly insecure.

**Comment by mikewest** [comment]
Closed in https://github.com/w3c/webappsec-csp/commit/22c3ab8ff872668b2454227e87427e8677f4db7c.

**Comment by mikewest** [comment]
Based on some conversation in https://bugs.chromium.org/p/chromium/issues/detail?id=648508, we might need to roll back this change to the spec. We certainly need to measure the impact on things like Cordova before landing it in Chrome again.

I'm curious whether you're seeing similar reports for Safari, @dbates-wk. Did you make this change in time for Safari 10?

**Comment by mikewest** [comment]
(It also appears that we might have just screwed up our patch. :) )

**Comment by dbates-wk** [comment]
> I'm curious whether you're seeing similar reports for Safari, @dbates-wk. 

No, we are not seeing similar reports. One of the motivations behind this proposed change was to avoid such reports.

> Did you make this change in time for Safari 10?

Yes.

**Comment by shekyan** [comment]
This change was never done in Chromium:(

**Comment by mikewest** [comment]
Yeah, sorry. I missed the context. We simply screwed up our implementation. Happily, caught it in beta! :)

https://codereview.chromium.org/2368073003 will take care of it for us. Sorry for the noise!
