### ISSUE TITLE
Specify behavior of preload requests

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#108]
This spec does not explicitly define how preload requests initiated by `<link rel=preload as=... href=...>` should be governed.

**Comment by annevk** [comment]
We did discuss this with @igrigorik and @mikewest. Does it not fall out of Fetch?

**Comment by igrigorik** [comment]
Yes, I believe it does. 

- Preload sets fetch destination: http://w3c.github.io/preload/#processing
- Fetch + CSP should be using that to enforce the right CSP directive.

**Comment by mikewest** [comment]
Right, this is done via the preload fetches setting the correct flags on the `Request`.
