### ISSUE TITLE
worth allowing embedded frame to declare origins it will accept any policy from?

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec-csp#118]
for advertising use case, requiring the exact policy to be reflected by the embeddee makes change management difficult; in effect you would have to pass the entire policy as part of the URL loading the ad to make sure the correct policy can be reflected in headers - probably lots of complexity for how broken that ecosystem is.

allow-csp-from: google.com facebook.com etc... 

might be more usable in practice.

**Comment by mikewest** [comment]
Or `CSP-Allow-Origin` to match `Timing`. Which raises the question about what we do with `*` that @annevk noted with regard to the latter. This is probably less interesting than timing data, so there's a reasonable argument for allowing opt-in via a simple `CSP-Allow-Origin` for the use-cases we care about at the moment, but I might be underestimating the leakage potential there via some combination of resource whitelisting and `report-uri`.

**Comment by mikewest** [comment]
Took a stab at this in https://w3c.github.io/webappsec-csp/embedded/#csp-allow-origin-http-header and the related algorithm changes. WDYT, @hillbrad?

/cc @Sun77789.

**Comment by annevk** [comment]
I think we should keep the named-like-CORS headers to where you share some data. As I understand it this is more about inheriting policy so the semantics are somewhat distinct.

Basically, this allows your embedder to find out about any resources you fetch, especially if they have some knowledge about you or if we allow policy modification at some point in the future. It might also your embedder to influence script execution, right?

**Comment by mikewest** [comment]
> I think we should keep the named-like-CORS headers to where you share some data.

Ok, so you see `*-Allow-Origin` as giving the embedder direct access to some bits and pieces of state, as opposed to enabling a feature that exposes data as a side-effect of it's core purpose. That seems reasonable. How about `Allow-CSP-From`? 

> Basically, this allows your embedder to find out about any resources you fetch, especially if they have some knowledge about you or if we allow policy modification at some point in the future. It might also your embedder to influence script execution, right?

Correct.

**Comment by annevk** [comment]
`Allow-CSP-From` seems fine.

**Comment by mikewest** [comment]
Done in https://github.com/w3c/webappsec-csp/commit/77dba9104c5a9d26009843a4a20c3764eae78c50. Thanks!
