### ISSUE TITLE
Chrome throws a SecurityError while Firefox does not

### ISSUE THREAD

**Issue by teddink** [w3c/webappsec-csp#120]
The Edge team is currently implementing CSP2 and we are onboarding the w3c/web-platform-tests for CSP. We found a couple of instances where Chrome and Firefox disagree.

Both browsers correctly block the action and send a CSP report.  However, sometimes additionally Chrome throws a SecurityError, while Firefox does not.

We haven’t been through all the tests yet, but the pattern seems to be that Chrome throws for actions that can only be instigated via `<script>`:
• When creating a new EventSource to a blocked URL, Chrome throws while FireFox quietly closes the connection.
• When using ‘sendBeacon’ to send to a blocked URL, Chrome throws while FireFox quietly sends nothing.

The [connect-src](https://w3c.github.io/webappsec-csp/#directive-connect-src) section of the spec seems to leave the correct behavior ambiguous. What is the expected behavior here?

**Comment by michaelficarra** [comment]
0. [`connect-src` Pre-request check ](https://w3c.github.io/webappsec-csp/#connect-src-pre-request) returns "Blocked"
0. [Should request be blocked by Content Security Policy?](https://w3c.github.io/webappsec-csp/#should-block-request) returns "Blocked"
0. [Main fetch step 5](https://fetch.spec.whatwg.org/#main-fetch) sets *response* to a network error.
0. The user agent then does whatever it's supposed to do with a network error from fetch in that particular context.

**Comment by annevk** [comment]
@teddink you should get an error event on `EventSource` in Firefox. I forgot how `sendBeacon()` surfaces network errors, I suppose it doesn't.

**Comment by mikewest** [comment]
> @teddink you should get an error event on EventSource in Firefox.

Indeed. We originally were throwing in `XHR`, `EventSource`, etc. @annevk convinced me to change it a million years ago, as it aligns the behavior between redirect blockage and non-redirect blockage, and simplifies the interface to Fetch. I thought we updated Chrome, but it's entirely possible that we didn't.

In other words, this sounds like a Chrome bug and not a spec bug. If you file a bug against Chrome, I'll get it fixed.

> I forgot how sendBeacon() surfaces network errors, I suppose it doesn't.

`sendBeacon()` is fire-and-forget. It doesn't surface errors, as its lifetime is decoupled from the context of the document.

**Comment by teddink** [comment]
Here you go Mike: [651879](https://bugs.chromium.org/p/chromium/issues/detail?id=651879#)

**Comment by mikewest** [comment]
This was fixed in https://github.com/Igalia/chromium/commit/8a4e051abc8f7a36687b5f45a214e9489b6a66b7.
