### ISSUE TITLE
Stop using whitelist as a term

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-csp#124]
In HTML we have used "safelist" / "blocklist" for a while to avoid the connotation that "white" is good and "black" is bad.

**Comment by annevk** [comment]
Quick search suggests this might also affect "Upgrade Insecure Requests" and "Secure Contexts" within WebAppSec.

**Comment by mikewest** [comment]
Thanks, @annevk. "safelist" and "blocklist" sound super-strange to me, but it seems like we can avoid these generic terms entirely in the few places we're using them by being more precise about what we mean. I've altered CSP, and I'll poke at the other documents you've mentioned shortly.

**Comment by annevk** [comment]
Well, they are a lot more descriptive than "white" and "black", so... But rephrasing seems okay too.

**Comment by mikewest** [comment]
Dropped from SECURE. I don't see the term in the current text for UPGRADE (though it was in earlier working drafts). A quick grep locally is only coming up with previously published drafts, so I'll leave this closed out.

Thanks for flagging this. I appreciate it.
