### ISSUE TITLE
SecurityPolicyViolation and shadow trees

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-csp#128]
So the new specification text hides `SecurityPolicyViolation` from the document when they occur in a shadow tree. I doubt that was intentional as it actually changes when the event reaches the document (no longer always).

`composed` should prolly be set to true.

Note that if the `SecurityPolicyViolation` class ever exposes information about the tree, you'll have to do extra steps for those, since we cannot expose shadow tree information to the outer tree.

@hayatoito @rniwa

**Comment by mikewest** [comment]
> I doubt that was intentional as it actually changes when the event reaches the document (no longer always).

Indeed.

> Note that if the SecurityPolicyViolation class ever exposes information about the tree, you'll have to do extra steps for those, since we cannot expose shadow tree information to the outer tree.

If we fire the event at the responsible element in the shadow tree, then it's `target` would be that element, which would leak its state if we allowed the event to bubble out of the shadow. If we tack the responsible element into a new attribute, we'd end up with the same problem.

As a concrete example, we fire a violation for the inline style element in https://jsbin.com/xozuto/edit?html,js. In Chrome's current implementation, this fires at the document, revealing nothing about the shadow DOM's innards. If we set `composed` on the event, it would bubble out of the shadow tree, providing a reference to the innards. That seems reasonable to me, but I don't understand what guarantees shadow DOM makes about its internals. It's not a security boundary, right? Why do we need to prevent information about the innards of the shadow tree from escaping?

**Comment by annevk** [comment]
No, while the event is outside the shadow tree (during capture and bubble) the target will actually point to the shadow host. Event dispatch is a lot trickier in the world of shadow trees (and you'll have multiple targets in a way).

**Comment by annevk** [comment]
It's not a security boundary, it's a private state boundary.

**Comment by mikewest** [comment]
> No, while the event is outside the shadow tree (during capture and bubble) the target will actually point to the shadow host. Event dispatch is a lot trickier in the world of shadow trees (and you'll have multiple targets in a way).

Ok. Is setting the `composed` attribute enough? It looks like handing the `target` attribute during bubbling is done in https://dom.spec.whatwg.org/#dispatching-events, but I'm out of my depth here.

**Comment by annevk** [comment]
Yeah, I think you'd just have to set `composed`. What I was saying is that if you later add custom fields pointing out tree information (not `target` or `relatedTarget`), you'll need to shield those somehow.

**Comment by mikewest** [comment]
Got it. I don't intend to do that, but I'll add a note to the spec.

**Comment by foolip** [comment]
Picking this to talk about another thing from https://twitter.com/mikewest/status/786532357100613632 and https://github.com/w3c/webappsec-csp/commit/60930fdeb01c041de30260d5496c9f8c3fd3e07b

There isn't much precedent here (fate of `webkitfullscreenchange` unclear) but I would perhaps say that if the element isn't connected, just fire the event on its node document. Or some other clearly defined document, https://codereview.chromium.org/2421473004/ doesn't use the node document.

That is, only fire the event on an element if a document, or perhaps some specific document, will be on the event path.

**Comment by mikewest** [comment]
@foolip: Would you mind spelling out a situation in a little more detail? I think we might be able to avoid the question you're raising for this particular feature, as it only applies to inline behaviors (event handlers, inline script/style blocks) which I don't think will be active in detached elements.

That is the following doesn't execute (and thereby produce a violation) until it's injected into the document:

```
var s = document.createElement('script');
s.innerText = "alert(1);"
document.head.appendChild(s);
```

Likewise, the following isn't parsed and applied until it's injected:

```
var s = document.createElement('style');
s.innerText = "p { color: red; }";
document.head.appendChild(s);
```

I guess you're worried about timing issues whereby the element is injected, a violation is fired, and the handler removes the element?

**Comment by annevk** [comment]
```var div = document.createElement("div")
div.setAttribute("onclick", "alert(1)")
div.click()```

**Comment by foolip** [comment]
I confess to not knowing what kinds of inline elements we were talking about, I assumed that CSP violations for `img` and similar was possible and would be reported using this event.

But yes, even if limited to only inline scripts and style, unless the event is fired synchronously when those elements are processed (unclear, and question on the code review) then it'll be possible for the element be removed *before* dispatch. Removing during dispatch doesn't matter, the event path has already been calculated then.

**Comment by mikewest** [comment]
Ok, based on more discussion with @foolip, I've landed https://github.com/w3c/webappsec-csp/commit/8b304c78c78ba86f7b2edb49e5315fd31bde36fc (which was supposed to point at this issue, but instead points at an entirely different repository. Oops.). Does that address your concern, @foolip?

**Comment by annevk** [comment]
Why would target be null?

**Comment by mikewest** [comment]
Target would be null if we don't have an element to assign to the violation. For instance, `<img src="whatever">` might violate `img-src 'none'`, but because we trigger the violation as part of Fetch, we can't tie it back to the element that caused the violation (without some fairly substantial work in HTML and Fetch to pipe the element through in all cases).

**Comment by annevk** [comment]
Ta, left some comments inline.

**Comment by foolip** [comment]
As did I. Only nits, the issues with removed elements are fixed though, thanks!
