### ISSUE TITLE
Having problems setting up "worker-src" help pls

### ISSUE THREAD

**Issue by ayumihamsaki** [w3c/webappsec-csp#130]
I thought I'd add worker-src as I have everything else in Level 3.

I seem to have three service workers on one of my webpages these are:

https://example.com/sw.js <--my one
https://connect.facebook.net/en_US/sdk.js <-- facebook widget one
http://example.com/assets/js/widgets.js <-- twitter widget (I transfered the JS file because I dont want them to change the code due to another CSP thing I got)

I have tried writing the code like this:

```
worker-src 'self' https://connect.facebook.net;
or
worker-src http://example.com https://connect.facebook.net;
or
worker-src http://example.com *.facebook.net;
or
worker-src http://example.com https://connect.facebook.net/*;
etc
```

Error Log from Google Canary:

(https://example.com/sw.js <-- passes fine)
sdk.js:81 Unrecognized Content-Security-Policy directive 'worker-src'.
widgets.js:1 Unrecognized Content-Security-Policy directive 'worker-src'.

Really not sure why but I can only seem to get my own website service worker to pass CSP and can't seem to get the Facebook or the Twitter working. I have done a search on the internet and on your w3c spec page. There is no examples out there with regards to external service workers.

I should add, the webpage worked 100% fine before I added the worker-src and let all service workers work fine in csp; as I wasn't csp white listing them. But I thought I have a go and add this to my list, as like I say I got everything else running ok in level 3 so I thought I try and take my CSP as far as I can go.

Going to tag three of the most clever people in this field into this post maybe they can help me:

@mikewest @igrigorik @annevk

**Comment by annevk** [comment]
I suspect you simply found a browser bug since this is a new feature. From the error messages it seems Chrome doesn't implement it.

Per https://w3c.github.io/webappsec-csp/#parse-serialized-policy that should lead to the directive being ignored, so the behavior being different from the default seems suspect, and might indicate another browser bug.

**Comment by mikewest** [comment]
Chrome doesn't yet implement `worker-src`. I don't think we have any special behavior for that directive, other than a console warning. It's on my list of things to implement this quarter, so, soon!

From your examples, it looks like you're trying to load a cross-origin script as a service worker? That's not something that service workers support; those scripts must be same-origin. The policy you apply to a page doesn't change that fundamental requirement.

**Comment by ayumihamsaki** [comment]
Thank you for your replies. This seems to be my usual problem following you guys and then testing all these new api's to find out that it's not yet implemented into Chrome yet. Will keep my eyes open for this in the near future. Funny same thing happened to be with GEO Fencing api and some RAIL api's you guys worked on.

Many thanks for your replies, I really don't know how you find the time to reply and do all your things. But love your work pushing the web forward.

**Comment by ayumihamsaki** [comment]
@mikewest Thanks for adding it. Using it fine today in Chrome V58.

**Comment by matthewp** [comment]
Aren't workers restricted to same-origin always, anyways? So `worker-src 'self' https://another.domain;` don't supersede the same-origin requirement. You can never create a worker that's on another.domain.

**Comment by dveditz** [comment]
The same-origin restriction applies to the worker itself, but it can import additional scripts from anywhere. Apart from "worker-src 'none'" preventing workers entirely, the directive mainly applies to these imported scripts.

**Comment by matthewp** [comment]
Thanks for the explanation @dveditz. I sort of feel like the worker-src CSP header should supersede the same-origin restriction here. I'm not sure if there is precedent for a CSP header granting *more* permissions though.
