### ISSUE TITLE
Deprecate child-src

### ISSUE THREAD

**Issue by briansmith** [w3c/webappsec-csp#145]
It seems it was agreed that it was a mistake to define `child-src` instead of defining `worker-src` and leaving `frame-src`. Now `frame-src` is un-deprecated and `worker-src` has been added, so `child-src` is just going to be a source of confusion, especially how it relates to the other two directives it overlaps with. It should be deprecated.

**Comment by mikewest** [comment]
I agree, thanks for filing the bug.
