### ISSUE TITLE
Clarification needed on location of Subtype key to indicate Alternate content-type

### ISSUE THREAD

**Issue by journeymansix** [w3c/webappsec-csp#159]
Here’s the rPDF spec’s statement on EmbeddedFile:
(Optional; PDF 2.x) When present, this dictionary shall be a
file specification dictionary (ISO 32000-2, 7.11.3) that shall
contain an EF key whose value is an embedded file stream
(ISO 32000-2, 7.11.4) containing the data for this presentation
in the file format appropriate for the value of Subtype.
**The MIME type of the embedded file shall be specified using
the Subtype key of the file specification dictionary**.

That original sentence could be made more specific by being modified to something like:
“The MIME type of the embedded file shall be specified using the Subtype key **of the embedded file stream** of the file specification dictionary.”
 
Ideally, an example should be supplied.

**Comment by mikewest** [comment]
I assume this is in relation to the `plugin-type` directive, but it's not clear to me what you're asking for. :) Is the grammar incorrect in the CSP spec?

**Comment by journeymansix** [comment]
Sorry, this is the wrong context for this. Withdrawing the issue.
