### ISSUE TITLE
`scheme-source` matching algorithm skips port matching

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#162]
In [6.6.1.6. Does url match expression in origin with redirect count?](https://w3c.github.io/webappsec-csp/#match-url-to-source-expression), if source-expression is a `scheme-source`, port matching is omitted. 

I don't think it is correct behavior because it still should check if port is a default port for the scheme in source-expression. 
E.g. `script-src http:;` should NOT match `http://example.com:8888`.

**Comment by mikewest** [comment]
Scheme-source allows anything for a scheme; I don't think there's much value in treating `https:` as different from `https://*:*`. The developer is already allowing every domain, what's the value in disallowing certain ports?

**Comment by shekyan** [comment]
I didn't realize this behavior was there forever, thinking it was recently introduced, so changing this would probably be backwards incompatible. However, surveying 3 unbiased developers revealed that all of them would assume that `default-src https:;` will match `https://example.com:443` and will not match `https://example.com:8443`.

**Comment by mikewest** [comment]
I don't think it's worthwhile to tighten this behavior now; as per some other outstanding bugs, we might be better off if we'd done things differently to begin with, but the opportunity this presents to attackers is small enough to not be worth the churn it would cause for developers relying on the existing behavior.
