### ISSUE TITLE
Clarify matching expressions with `host-source` but without `scheme-source`

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#166]
In [6.6.1.6. Does url match expression in origin with redirect count?](https://w3c.github.io/webappsec-csp/#match-url-to-source-expression), part of the algorithm covering matching expression with `host-source` but without `scheme-source` notes: 
> Note: As with scheme-part above, we allow schemeless host-source expressions to be upgraded from insecure schemes to secure schemes.

However, I don't see how the algorithm is covering noted.

**Comment by shekyan** [comment]
Also, it'd be nice to clarify the relation of expression to the origin scheme, if scheme-source is missing. 
Should `default-src *:*` served from `javascript:` match `http://example.com` ?

**Comment by mikewest** [comment]
The upgrade is allowed through the algorithm in https://w3c.github.io/webappsec-csp/#match-schemes (if it's an exact match, wonderful. if not, `http` matches `https`, etc).

For the second point, do you think that `*` shouldn't match `http` in that scenario? If not, why not?

**Comment by shekyan** [comment]
> The upgrade is allowed through the algorithm in https://w3c.github.io/webappsec-csp/#match-schemes (if it's an exact match, wonderful. if not, http matches https, etc).

For a policy `script-src example.com` served from `http://example.com`, a resource at `https://example.com/resource` would not match, as it falls through step 3.2 of 6.6.1.6., which passes `null` and resource's URL scheme, which returns "Does Not Match". I don't think that is intended.

**Comment by shekyan** [comment]
> For the second point, do you think that * shouldn't match http in that scenario? If not, why not?

I think it should match `http`, and previously, as I recall, it was doing so in the spec. Now, however, I can't find the algorithm that covers that.

**Comment by mikewest** [comment]
Thanks! I've addressed this in https://github.com/w3c/webappsec-csp/commit/309b2934842e2931a3573cd27db5fbe6caf478d1 by passing in the document's origin's scheme rather than `null`. I think that was the original intent.

Thanks!
