### ISSUE TITLE
"Does path A match path B?" is incorrect

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#171]
[Path matching algorithm](https://w3c.github.io/webappsec-csp/#match-paths) needs to be fixed up, as strict splitting removes context about U+002F SOLIDUS character (/) positions.

Consider two paths `/a` and `/a/`. Algorithm should return "Not Match". However, it returns "Matches":
*exact match* is false, *path list A* and *path list B* are identical, containing  `["", a]`. 

Similarly, two paths: `/a/` and `/a` should "Not Match", but current algorithm produces the opposite.

**Comment by shekyan** [comment]
Problem here is in the [Strict splitting](https://html.spec.whatwg.org/multipage/infrastructure.html#strictly-split-a-string). As HTML specification doesn't seem to reference it anywhere, we'll try to fix it there, and update this issue.

**Comment by mikewest** [comment]
Merged your patch, thank you!
