### ISSUE TITLE
Spec refers to "subresource" Fetch destination

### ISSUE THREAD

**Issue by yoavweiss** [w3c/webappsec-csp#172]
When going over the spec as I'm modifying Fetch's destination (for https://github.com/whatwg/fetch/pull/442), I noticed that there are multiple references to a "subresource" Fetch destination (e.g. at https://w3c.github.io/webappsec-csp/#connect-src-pre-request), which is no longer a thing.

IIUC, these should be modified to the empty string (or to the "fetch" destination, once my change to Fetch lands). I could also modify my PR to change the destination value back to "subresource" if that would help avoid churn.

**Comment by mikewest** [comment]
Thanks, @yoavweiss! Fixed in https://github.com/w3c/webappsec-csp/commit/3637991775ffe4a10a512e0f007a99b0a24ab036.
