### ISSUE TITLE
"http://*:80" is a valid source-expression but doesn't match "http://example.com:80"

### ISSUE THREAD

**Issue by ArthurSonzogni** [w3c/webappsec-csp#176]
**The current ABNF:**
```
source-expression = scheme-source / host-source / keyword-source / nonce-source / hash-source
host-source       = [ scheme-part "://" ] host-part [ ":" port-part ] [ path-part ]
host-part         = "*" / [ "*." ] 1*host-char *( "." 1*host-char )
```
It means that "http://*:80" is a valid source-expression
The problem is that the url: "http://example.com:80" doesn't match this source-expression.
That's counter-intuitive.

**Why it doesn't match?**
In https://w3c.github.io/webappsec-csp/#match-url-to-source-expression
In 1) The source-expression is not the string "*".  Thus we continue.
In 3) The source-expression matches the host-source grammar.
In https://w3c.github.io/webappsec-csp/#match-hosts. The hosts don't match because "a.com" doesn't end with a dot.

**Alternative:**
Maybe we could disallow a wildcard in the host if the remaining part is empty. The "*" source-expression could be caught by the first rule.
```
source-expression = "*" / scheme-source / host-source / keyword-source / nonce-source / hash-source
host-part         =  [ "*." ] 1*host-char *( "." 1*host-char )
```

It will make the following source-expressions invalid:
* http://*
* *:80
* */path

What do you think?

**Comment by shekyan** [comment]
> In https://w3c.github.io/webappsec-csp/#match-hosts. The hosts don't match because "a.com" doesn't end with a dot.

Arguments of "6.6.1.10. Does path A match path B?" are "*" and "example.com".
1 ) So it falls through step 1, and *remaining* is "".
2) *remaining* is case-insensitive match for rightmost characters of B, so it matches. 

As it matches in every browser implementation I checked. For clarity, look at our [implementation](https://github.com/shapesecurity/salvation/blob/master/src/main/java/com/shapesecurity/salvation/directiveValues/HostSource.java#L104) of host-part matching.

**Comment by ArthurSonzogni** [comment]
You are absolutely right! Thanks!
There was a sentence in the specification which I had misunderstood.
The specification is correct.

I found a bug in chrome when host-part = "*".
For instance, if source-expression = "http://*:111" then "http://example.com:222" is allowed.
I will try to fix it.
