### ISSUE TITLE
Potential problem with CSP reporting

### ISSUE THREAD

**Issue by nico3333fr** [w3c/webappsec-csp#181]
Hi there,

I don't know if this issue has already discussed (my apologies if it is the case) and even if it is already technically possible to handle it, but let's try : if I set up CSP directives with a report-uri, everyone can see for example on my website that there is a script that gets CSP issues (so JSON content).

If an attacker sends a lot of JSON requests on it, it might be complicated to find out which ones are good. 

So here is my question: would it be possible to have a system (in the browsers or whatever) that can mitigate this potential problem ?

**Comment by mikewest** [comment]
I agree with you that having an open endpoint invites abusive requests. I don't think CSP can address this, however, as it's not unique to the `report-uri` endpoints. The same risks apply to any API endpoint you expose to the open web.

I'd suggest that your best bet is to apply the same rate-limiting and abuse protection strategies to your API endpoints that you apply to your site at large (or to contract out to proxy services like Cloudflare that aim to prevent this kind of abuse at scale on your behalf).
