### ISSUE TITLE
`frame-ancestors` and `x-frame-options`

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-csp#182]
I should copy/paste https://www.w3.org/TR/CSP2/#frame-ancestors-and-frame-options over to CSP3. Ugh.

**Comment by annevk** [comment]
Maybe formally define both this time around?

**Comment by dveditz** [comment]
What do you mean? XFO is defined at https://tools.ietf.org/html/rfc7034 and frame-ancestors is defined right above Mike's link. Does https://w3c.github.io/webappsec-csp/#frame-ancestors-navigation-response count as "more formally"?

**Comment by annevk** [comment]
Something that defines them as a modification of HTML's navigate algorithm. So it's clear when the block occurs and what it means to events, lifecycle of objects, etc.

So the last link might work, provided it has the appropriate integration.

**Comment by mikewest** [comment]
We did start working on this: see step 1 of https://html.spec.whatwg.org/#process-a-navigate-response.
