### ISSUE TITLE
Add onsecuritypolicyviolation to the spec

### ISSUE THREAD

**Issue by LoonyBean** [w3c/webappsec-csp#184]
securitypolicyviolation event was discussed in the spec but not the event handler. Can we please add the event handler in the spec to standardize Document#onsecuritypolicyviolation?

@mikewest 

Thanks

**Comment by shekyan** [comment]
Event handlers are covered in [HTML spec](https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-attributes) and securitypolicy and `SecurityPolicyViolationEvent` shouldn't be an exception. 

BTW,  it fires on [global object](https://w3c.github.io/webappsec-csp/#report-violation), and not on the document.

**Comment by LoonyBean** [comment]
Some events have their own event handlers. If the event belong to global event handler, there should be a partial interface for the event handler. This event only exists on Document in Blink. If there should be a spec, this should be the right place to do it.

**Comment by zcorpan** [comment]
Event handlers that exist on document are generally added to [`GlobalEventHandlers`](https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers). So I think if you do it in the CSP spec you can do `partial interface GlobalEventHanders { ... }`, but upstreaming directly to HTML seems reasonable to me as well.

**Comment by mikewest** [comment]
Upstreaming this in https://github.com/whatwg/html/pull/2651. Thanks!

**Comment by domenic** [comment]
This can now be closed, as it's landed in HTML.
