### ISSUE TITLE
"fetch" is not a valid request initiator value

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec-csp#185]
https://w3c.github.io/webappsec-csp/#effective-directive-for-a-request has:

> If the request’s initiator is "fetch", return connect-src.

But the fetch spec has:

> A request has an associated initiator, which is the empty string, "download", "imageset", "manifest", or "xslt". Unless stated otherwise it is the empty string. 

so that condition will never match.  In practice, what this means is that the effective directive for a `fetch()` call, as currently specified, is `null`.  I suspect that's not what you want.

**Comment by mikewest** [comment]
Yup. Fetch moves quickly, for better or worse. Looks like this should now be "initiator, destination, and type are all the empty string". Which is somewhat less than explicit, but whatever.

Thanks!

**Comment by mikewest** [comment]
Fixed in https://github.com/w3c/webappsec-csp/commit/eaee204cc19fe883d49074f4e206aef6bb2d184e. Thanks!
