### ISSUE TITLE
Add ability to specify the version of used CSP

### ISSUE THREAD

**Issue by oxdef** [w3c/webappsec-csp#189]
Hello!

It is awkward to maintain backward compatible CSP policy, e.g. keep in it `unsafe-inline` with nonce for CSPv1 or `frame-src`/`child-src`. It looks like in the future versions of CSP such problem will be more obvious. In **some cases** in web application it is easer to have support of only the last one standard.  What do you think about adding ability to specify the version of used CSP? It can be done in header name like:
```
Content-Security-Policy-v3: ...
```
If browser meets more the one CSP header it should use header with the latest support version.

**Comment by mikewest** [comment]
I do not intend to do this in CSP3. While I agree that it's awkward to maintain backwards compatibility, I believe it's even more awkward for both developers and user agents to maintain support for several versions of the policy language. We've thus far been successful at iteratively improving the language over time. It absolutely has warts I'd dearly love to remove, but the benefits of monolithic improvement over time seem valuable enough to maintain.

That said, I'm all for explorations of what a "modern" take on CSP might look like. Given what we've learned over the last few years, maybe we'd do something simpler in a new header. That seems more likely to be a reasonable route to take than tacking versioning on to the existing system.
