### ISSUE TITLE
CSP3: handling paths for redirected targets will be safe again

### ISSUE THREAD

**Issue by ghost** [w3c/webappsec-csp#190]
Paths matching had been dropped for redirected targets because of security reasons:
https://www.w3.org/TR/CSP2/#source-list-paths-and-redirects

Please correct me if I'm wrong:

Since in CSP3  violation report will contain the original URL of any blocked request, rather
than the origin of the redirect target:

https://w3c.github.io/webappsec-csp/#create-violation-for-request

I think it is safe to get back to matching paths again for redirected targets, since redirected target won't be revealed in violation report any more.

**Comment by annevk** [comment]
The problem is exposing details of redirects to begin with. So I don't think this would be safe.

**Comment by mikewest** [comment]
I also don't think it's safe. The violation report is one leakage vector that we've eliminated. We haven't, however, eliminated the signal that a given request does or does not pass a given policy.

For example, consider a URL that redirects based on a user's signed-in status: `https://example.com/profile` -> `https://example.com/mikewest` or `https://example.com/login`. By constructing a policy like `child-src https://example.com/profile https://example.com/login`, a violation report will be sent for every signed-in user.

This can, of course, be extended to get more detailed information by adding more and more potential redirection endpoints to the policy and waiting for violation reports.

Stripping the path after a redirect is an attempt to mitigate the risk of this kind of attack. I don't think we've mitigated it if we don't retain that behavior.
