### ISSUE TITLE
"Does request violate policy" algorithm 6.6.1.1 doesn't accumulate violated directives

### ISSUE THREAD

**Issue by chaals** [w3c/webappsec-csp#195]
It seems that the goal of 6.6.1.1 is to get a *set* of directives which are violated. (Or maybe it just seems to me that it should be).

But the algorithm only provides the last directive in the policy that is violated.

I'll write a PR to change this. If the current algorithm behaviour is intentional, feel free to close.

**Comment by mikewest** [comment]
I think the current algorithm's behavior matches what we actually want to do: determine whether a request matches the policy or not. Punting out as soon as we have a violation seems like a reasonable way of doing that, and the use case discussed in the PR doesn't seem compelling-enough to justify the additional complexity.

If you disagree, @chaals, please do reopen and we can discuss.

**Comment by chaals** [comment]
It clearly didn't compel anyone else to speak up for it, so I agree that we can just close this.
