### ISSUE TITLE
CSP: make available a reliable method for obtaining a reference to the global object

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-csp#2]
_From @michaelficarra on October 6, 2015 23:38_

At times, it is necessary to obtain a reference to the global object. In different environments, this object has non-standard, writable self-references: `global` in node, `window` in certain browser contexts, `self` in other browser contexts, etc. It is not a good practice to rely upon these references. For this reason, a particular pattern using the `Function` constructor is the only reliable method (of which I'm aware) for obtaining a reference to the global object in any context (strict/sloppy mode, module/script).

``` js
var honestToGodGlobalObject = Function("return this")();
```

Because this is a use of the `Function` constructor, CSP does not allow this pattern without adding `'unsafe-eval'` to my policy. How can we make an exception to allow this pattern or something equivalent?

_Copied from original issue: w3c/webappsec#501_

**Comment by mikewest** [comment]
_From @hillbrad on October 6, 2015 23:39_

Is this an ECMAScript issue?

**Comment by mikewest** [comment]
_From @michaelficarra on October 7, 2015 0:10_

It could be solved from the ECMAScript side, but there's [little hope of that happening](https://esdiscuss.org/topic/putting-global-reference-in-specs). All I ask is that this particular pattern (or the `(0, eval)("this")` equivalent mentioned in the linked thread) be allowed because of its uncontested utility.

**Comment by mikewest** [comment]
If JavaScript isn't giving you the thing you need in a consistent way, I think you'll need to poke at JavaScript to solve your problem. :( In fact, it's entirely possible that folks would use CSP specifically to prevent you from grabbing access to the global object as part of a larger sandboxing mechanism. I don't think there's much value in carving out loopholes.

More practically, I don't think there's a good way to distinguish "safe" usage of `Function` or `eval` from non-safe usage. What you want is a well-defined `global` reference, not a pile of hacks.

**Comment by michaelficarra** [comment]
That's a totally reasonable position to have. It just doesn't appear that either side is willing to budge on this one, and legitimate use cases are stuck in limbo until something changes.

**Comment by michaelficarra** [comment]
FYI, there is now a stage 1 ECMA-262 proposal for exactly this. It has strong committee support. https://github.com/tc39/proposal-global

**Comment by mikewest** [comment]
Closing this out in favor of the JavaScript-side `global` proposal, which looks to be moving along (at stage 3 right now).
