### ISSUE TITLE
Consider a style-src keyword to allow style attributes but not <style> elements

### ISSUE THREAD

**Issue by arturjanc** [w3c/webappsec-csp#202]
Based on the discussion in https://github.com/whatwg/html/pull/2373 it seems like it might be useful to allow inline `style` attributes while requiring full stylesheets loaded via `<style>` or `<link rel=stylesheet>` to have a valid nonce/hash. This would let developers add `style-src` to their policies because they could keep existing `style` attributes, and would limit attackers because `style` attributes, unlike `<style>` elements, cannot use selectors, import external stylesheets, etc.

There is probably some complexity in making such a keyword backwards compatible to make sure it plays well with CSP3 and CSP2 browsers, so I'm not sure how to do this elegantly, but we should think about it.

**Comment by mikewest** [comment]
Duping this into #45.
