### ISSUE TITLE
A question about "A server SHOULD NOT send more than one [CSP header]"

### ISSUE THREAD

**Issue by bluetech** [w3c/webappsec-csp#216]
[Section 3.1](https://w3c.github.io/webappsec-csp/#csp-header) of the specification says:

> A server SHOULD NOT send more than one HTTP response header field named "Content-Security-Policy" with a given resource representation.

From my understanding, sending multiple policies is not a bad thing, and even encouraged, e.g. one with whitelist authored by the developer and one with `strict-dynamic` generated by the web framework. It also has an [entire section](https://w3c.github.io/webappsec-csp/#multiple-policies) dedicated to it.

I know "SHOULD NOT" has a very specific RFC meaning, but perhaps it should be changed to "MAY"? Or removed entirely, since it is implied by

> Content-Security-Policy = 1#serialized-policy

Thanks!

**Comment by devd** [comment]
I think you can send multiple policies in the same header: the idea is to tell developers to only send one header that has all the policies.

**Comment by bluetech** [comment]
Yes, according to [RFC7230 3.2.2](https://tools.ietf.org/html/rfc7230#section-3.2.2) they are equivalent.

So, the purpose of the paragraph is to recommend using

```
Content-Security-Policy: <policy-1>, <policy-2>
```

Over

```
Content-Security-Policy: <policy-1>
Content-Security-Policy: <policy-2>
```

? I am curious why the 2nd form is preferred, but that's good enough for me (the web framework I work with doesn't support multiple headers with the same field name, anyway).

Thanks!
