### ISSUE TITLE
EE: Rename `Required-CSP` to `Sec-Required-CSP`

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-csp#219]
I know we just renamed this, but while the bikeshed door's still open, we should give the header a `Sec-` prefix to ensure that the user agent remains in control over the content (and that it's not injected via XHR, `fetch()`, or etc.

@andypaicu, mind taking this? :)

**Comment by andypaicu** [comment]
I have submitted a PR

**Comment by andypaicu** [comment]
https://github.com/w3c/webappsec-csp/pull/220
