### ISSUE TITLE
'unsafe-inline', 'unsafe-eval', nonce-source, hash-source are no-op for most of the source-list directives

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#22]
While `'unsafe-inline'`, `'unsafe-eval'`, `nonce-source`, `hash-source` are valid `source-expression` values, only default-src, script-src and style-src define parsing for above keywords.
It would make sense to define something like `executable-source-expression` with appropriate grammar and use it for default-src, script-src and style-src, while make other source-list directives use `source-expression`.

**Comment by mikewest** [comment]
I'm not sure if that complexity is worthwhile. That is, `'unsafe-eval'` certainly doesn't do anything for `connect-src`, but that's fine, because user agents ignore it during the matching algorithm, and they don't have to special-case the parser for any of the fetch directives.

What's the down side to accepting these in the grammar, but ignoring them?

**Comment by shekyan** [comment]
Maybe, to make things clear for the implementers,  explicitly mention in the spec that nonce-source, hash-source, `'unsafe-eval' ` and `'unsafe-inline'` are ignored while parsing for the rest of the directives. I agree that introducing new grammar will make things complicated.

**Comment by shekyan** [comment]
Another reason to separate executable contents' grammar is to minimize policy length:
```
Content-Security-Policy: default-src 'nonce-123'; script-src 'nonce-123'; style-src 'nonce-123'
```
can be optimized into `default-src 'nonce-123'`. 
But if one implements spec compliant parser, the optimization would happen only if every single directive type that consumes `source-list` is explicitly specified.

**Comment by mikewest** [comment]
1. Optimizers should be free to use their understanding of implementation quirks to do The Right Thing(tm) for the code. :)

2. It's not clear that that's a safe transformation forever and ever. That is, requests like https://github.com/w3c/webappsec-csp/issues/15 would break the assumption you're making about nonces' applicability. More generally, there's no reason that a nonce _couldn't_ be applied to things like images or forms or XHR or whatever. *shrug*

**Comment by shekyan** [comment]
But then you can't call it spec compliant optimizer. Hard choice. Feel free to close the issue.
