### ISSUE TITLE
Permission for browser extensions

### ISSUE THREAD

**Issue by leodutra** [w3c/webappsec-csp#232]
I want to create a browser extension which can load a remote HTML and render. Although, I want just my extension (or at least extensions) to do this and not every iframe in any site.

Maybe using an RSA: `web-extension: 'rsa-4527874AB...' `.

I don't know if it is possible because I have never read the full spec, just reference manuals.
If it is not possible now, please consider the case. It is very recurrent on extension development across the years.

Thanks.

**Comment by andypaicu** [comment]
Hmm it's not clear to me what you're proposing here. Are you basically asking for a directive that allows websites to limit what extensions are allowed to do?

**Comment by leodutra** [comment]
Right now, extensions cannot be specifically allowed by CORS.

I'm proposing a RSA / OAuth based approach for extension allowance.
