### ISSUE TITLE
Case-sensitivity resulting in divergent browser behavior

### ISSUE THREAD

**Issue by april** [w3c/webappsec-csp#236]
In the process of rewriting the [Observatory](https://github.com/mozilla/http-observatory)'s CSP parsing code, I discovered that browsers have divergent behavior with regards to case-sensitivity in directives.

For example, this policy:

`Content-Security-Policy: SCRIPT-SRC 'none'`

Will allow inline script to execute in Chrome, but not in Firefox, Safari, or Edge, as you can see in the [live demo](https://www.twoevils.org/html/test/csp-case-sensitivity-1.html).

Similarly, this policy:

`Content-Security-Policy: UPGRADE-INSECURE-REQUESTS`

Will cause Firefox and Safari to upgrade insecure requests, but not Chrome, resulting in Chrome generating a [mixed-content warning](https://www.twoevils.org/html/test/csp-case-sensitivity-2.html).

As near as I can tell, the specification itself only explicitly states the following should be case-sensitive:

1) paths on URIs
2) nonces

For directives, it doesn't explicitly state whether they're case-sensitive or not. This is pretty odd, as it's generally explicit about case-sensitivity or insensitivity for everything else. We probably need to decide on which behavior is better with regards to directives. 

Either way, we are going to need some web platform tests and should probably be more clear about behavior in either 2.1.1. Parse a serialized CSP as disposition or possibly in the pre-flight check sections.

**Comment by april** [comment]
cc: @dveditz, @mikewest

**Comment by dveditz** [comment]
CSP2 implied case-insensitive https://w3c.github.io/webappsec-csp/2/#policy-parsing

But actually that might be saying that a policy with SCRIPT-src and script-src could have the "real" script-src hidden by a SCRIPT-src that's parsed first, but then SCRIPT-src isn't script-src so it's ignored. That behavior doesn't make sense but that seems to be one way to read it.

**Comment by dveditz** [comment]
If this is an intentional parsing change in CSP3 it probably should be mentioned in https://w3c.github.io/webappsec-csp/#changes-from-level-2 although hopefully not too many people were using uppercase directive names.

**Comment by andypaicu** [comment]
I think this is an oversight more than a decision to move from CSP2 behaviour. I think case-insensitive directive name parsing makes sense.
I will discuss with some people at Chrome but I doubt there will be any concerns with bringing Chrome inline with the other browsers.
