### ISSUE TITLE
Remove worker references from child-src section

### ISSUE THREAD

**Issue by dveditz** [w3c/webappsec-csp#239]
Section 6.1.1 child-src says

> The child-src directive governs the creation of nested browsing contexts (e.g. iframe and frame navigations) and Worker execution contexts

Elsewhere (e.g. "Changes from Level 2", the script-src and default-src algorithms) a missing worker-src is defined to fall-back to script-src and then default-src, with no child-src.

[NB: the CSP3 re-definition of worker-src will break some existing users of CSP, both those who already assumed workers were scripts but have a bug as well as those who were doing the right thing with child-src and intentionally covering workers that way. Hopefully not too many sites]

**Comment by ckerschb** [comment]
After chatting with Mike it seems that Chrome has the following fallback in place:
* worker-src
* child-src
* script-src
* default-src

I think that is also the way that Firefox would like to implement it. Can we get the spec updated to reflect that behavior?

**Comment by mikewest** [comment]
Ping @dveditz @ckerschb on the above?

**Comment by ckerschb** [comment]
I would be happy to remove the extra fallback but it seems the 'multiple' fallback option is the best we have at the moment. To summarize:

1) For frames we are definitely on the same page. If frame-src is present, then frame-src is used, falling back to child-src and ultimately default-src.

2) For workers, we first check if worker-src is present, if not, we check if child-src is present, if not, we check if script-src is present, if not, then ultimately default-src governs workers.

It would be easy to eliminate the child-src in between in Firefox' implementation, but given your breakage study I would rather go down that route of having multiple fallbacks.

**Comment by mikewest** [comment]
Ok, so you're planning on shipping `frame-src` -> `child-src` -> `default-src` on the one hand, and `worker-src` -> `child-src` -> `script-src` -> `default-src` on the other?

@andypaicu: Are you on board with speccing and implementing that in Chrome?

**Comment by andypaicu** [comment]
Yeah I'll take care of it
