### ISSUE TITLE
Year of CSP3 is 2016

### ISSUE THREAD

**Issue by alexmuller** [w3c/webappsec-csp#244]
This might be my misunderstanding but it's really confusing me.

https://www.w3.org/TR/CSP2/ as a W3C Recommendation has a date of 15 December 2016.

https://www.w3.org/TR/CSP3/ as a W3C Working Draft has a date of 13 September 2016.

Should the second date be 2017?

**Comment by alexmuller** [comment]
Also the "Latest version in series link" on https://www.w3.org/TR/CSP2/ has link text of https://www.w3.org/TR/CSP/ but a link target of https://www.w3.org/TR/CSP2/ - not sure if this is intended.

**Comment by annevk** [comment]
Latest is https://w3c.github.io/webappsec-csp/, nothing else really matters. I'd recommend trying to stay away from TR/ as it's a confusing place (and sometimes joked as standing for "trash").
