### ISSUE TITLE
A kind of a nonce for a complete "zone"

### ISSUE THREAD

**Issue by nico3333fr** [w3c/webappsec-csp#245]
Hi there,

Let's imagine the case: you have rather clean CSP directives (no unsafe-inline JS/CSS etc.) for a full website and you have to manage an external script that inject junk in the page that is out of control.

``` 
<div nonce="12345">
the piece of crap here, for example a script that insert HTML code with inline styles attributes, etc.
</div>
```

For example: ```ignore-src: "nonce-12345"``` which does not apply CSP directives in it. How could it be possible, without removing all CSP directives to allow this part to ignore CSP directives, without creating dangers ? 
(I do agree the idea is not perfect, however, this is a real issue that I may encounter deploying CSP with some services that are not CSP-friendly)

**Comment by andypaicu** [comment]
I think it would be very dangerous to implement something like this as you can't really make any guarantees for the rest of the page if you give blanket permissions some external script.

Have you had a look at `strict-dynamic` (https://w3c.github.io/webappsec-csp/#strict-dynamic-usage). It seems unlikely to work if the script is too crazy but maybe it helps.
