### ISSUE TITLE
Optional path-abempty part makes no sense

### ISSUE THREAD

**Issue by notriddle** [w3c/webappsec-csp#249]
The [`path-abempty`](https://tools.ietf.org/html/rfc3986#section-3.3) syntax of RFC 3986 is defined such that it can match an empty string `""`.

The [`host-source`](https://www.w3.org/TR/CSP/#grammardef-host-source) syntax of the CSP specification allows the `path-part` to be left out.

This is ambiguous; should `google.com` parse as a Host Source with no path part, or should it parse as a Host Source with a path part that is empty?

I assume the former, so it should probably be changed to an optional `path-absolute`.

**Comment by andypaicu** [comment]
https://github.com/w3c/webappsec-csp/pull/250

**Comment by mikewest** [comment]
Thanks for the report, @notriddle, and the patch, @andypaicu!
