### ISSUE TITLE
Allow https: loads for http: restrictions

### ISSUE THREAD

**Issue by ckerschb** [w3c/webappsec-csp#25]
Similar to what applies to schemeless resources where CSP allows https: loads, the spec should be changed to also allow https: loads to succeed if the CSP src is defined as http:

In easier words, taken a CSP:
>>  img-src http:
the CSP should allow loading https: images.

**Comment by mikewest** [comment]
I've thought about this a bit this morning after chatting with @tanvihacks and @rlbmoz, and I think it makes sense to always allow upgrades from insecure resources to secure resources at the same host and path. That is, if we do this for `http:`, we might as well do it for `http://example.com` and `'self'` as well. I'll take a stab at this and #7 together, as they end up touching the same pieces.

**Comment by mikewest** [comment]
Poked at this in https://github.com/w3c/webappsec-csp/commit/0e81d81b64c42ca3c81c048161162b9697ff7b60. WDYT?
