### ISSUE TITLE
Don't use `not-example.com` in examples.

### ISSUE THREAD

**Issue by tomprince** [w3c/webappsec-csp#264]
[RFC 6761](https://tools.ietf.org/html/rfc6761) provides a top-level example domain, among others, so a real domain doesn't need to be used in examples.

**Comment by mikewest** [comment]
Yeah. `example.com` and `not-example.com` seemed more clearly distinct to me than `example.com` and `example.org`, but you're entirely correct. Thanks!

**Comment by annevk** [comment]
@mikewest well, you can use corp.example or some such too.
