### ISSUE TITLE
Line and column number types

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-csp#268]
Status is a non-negative integer and represented as unsigned short in IDL. Line and column number are non-negative integers and represented as long. Why not unsigned long?

(It's also rather unfortunate their names are not equivalent to those on ErrorEvent as defined in the HTML Standard: `lineno` and `colno`.)

cc @domenic @smaug----

**Comment by domenic** [comment]
What is this referring to? https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md doesn't mention anything about status, line, or column numbers.

**Comment by annevk** [comment]
https://w3c.github.io/webappsec-csp/#violation-events

(This is not a WebAssembly repository.)

**Comment by domenic** [comment]
Thanks, I got confused switching between emails/tabs.

**Comment by andypaicu** [comment]
Fixed the type, will fix the names
