### ISSUE TITLE
missing local / network scheme definition in URL spec

### ISSUE THREAD

**Issue by dhausknecht** [w3c/webappsec-csp#272]
* "local scheme" is linked to https://url.spec.whatwg.org/#local-scheme
* "network scheme" is linked to https://url.spec.whatwg.org/#network-scheme

Both terms are not defined in the linked URL standard. In fact they do not even appear in there at all.

**Comment by annevk** [comment]
Sorry, I forgot that CSP depends on them. They moved to Fetch.

**Comment by annevk** [comment]
Note that this is already fixed in https://w3c.github.io/webappsec-csp/.

**Comment by dhausknecht** [comment]
oh, okay. Not on https://www.w3.org/TR/CSP3/. But I think in that case I can close it as resolved nevertheless. Thx

**Comment by annevk** [comment]
I recommend not reading TR/.

**Comment by dhausknecht** [comment]
The problem for academia in https://w3c.github.io/webappsec-csp/ is the following:

> This is a public copy of the editors’ draft. It is provided for discussion only and may change at any moment. [...] Don’t cite this document other than as work in progress.

Therefore I kind of need TR unfortunately :-(
