### ISSUE TITLE
CSP vulnerability enabling cross-origin session data exfiltration

### ISSUE THREAD

**Issue by eligrey** [w3c/webappsec-csp#289]
Consider the vulnerability described by @Zemnmez in 2014: https://archive.is/UXD8j

The solution is to have CSP-allowed URIs confer trust to all redirected URIs.

If you trust the content at a URI, then you should also trust any redirects that it makes. Implementing this change fixes the vulnerability while staying compatible with the goals of CSP.

**Comment by albinowax** [comment]
I believe this issue was fixed a while ago by making browsers disregard path requirements after redirects: https://www.w3.org/TR/CSP11/#source-list-paths-and-redirects

**Comment by eligrey** [comment]
Oh, I wasn't aware that it was fixed. I did some cursory searches in the spec and didn't find that at first. Thanks for letting me know that it's no longer an issue!
