### ISSUE TITLE
NIST URls support https now

### ISSUE THREAD

**Issue by edent** [w3c/webappsec-csp#294]
![nist](https://user-images.githubusercontent.com/837136/36345255-13c9f10a-141f-11e8-99b2-39fc47ecf08c.png)

See https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf#

Probably needs to be fixed upstream.

**Comment by annevk** [comment]
No, needs to  be fixed in https://github.com/w3c/webappsec-csp/blob/master/index.src.html#L131.

**Comment by annevk** [comment]
It seems a bunch of other `http:` URLs can be updated too.
