### ISSUE TITLE
Directive to disallow external entities in SVG/XML?

### ISSUE THREAD

**Issue by Malvoz** [w3c/webappsec-csp#300]
[OWASP's top 10 security vulnerabilities [PDF]](https://www.owasp.org/images/7/72/OWASP_Top_10-2017_%28en%29.pdf.pdf) explains that an SVG (file or inline in HTML documents) that includes reference(s) to external entities "may lead to the disclosure of confidential data, denial of service, Server Side Request Forgery (SSRF)" - [OWASP XXE prevention cheat sheet](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#Introduction).

More information on security issues/example attacks:
https://www.owasp.org/images/0/03/Mario_Heiderich_OWASP_Sweden_The_image_that_called_me.pdf

I don't know if this can be restricted using CSP, the OWASP prevention cheat sheet states that DTDs should be disabled to secure **the parser**. But I figure, if you do not control the parser, CSP could have a directive to not allow for external references inside SVG/XML in the first place.

Feel free to close the issue if this is inapplicable.

**Comment by annevk** [comment]
Is there any browser that does something with such entities? I'm pretty sure that's not the case so I think this attack doesn't exist as far as browsers goes.

**Comment by Malvoz** [comment]
I suppose this is somewhat covered in https://github.com/w3c/webappsec-csp/issues/198, I'll go ahead and close this. Thanks!
