### ISSUE TITLE
I want all links on my website to be rel=noopener

### ISSUE THREAD

**Issue by kdzwinel** [w3c/webappsec-csp#316]
There were three related topics being discussed at the same time in https://github.com/w3c/webappsec/issues/139:

1. how a website can say "I want all my links to be `rel=noopener`!" (so that the openee can't send me any messages)
2. how a website can say "I want to always be opened as if `rel=noopener` was set on a link that opened me!" (so that the opener can't send me any messages)
3. how the API for 1 and/or 2 should look like (CSP? separate header? etc.)

https://github.com/w3c/webappsec-csp/issues/194 follows up on 2 & 3, but @annevk suggested I should open a new issue for 1.

**Comment by andypaicu** [comment]
I think https://github.com/whatwg/html/issues/3740 is relevant. I don't think CSP will do this in the near future.

**Comment by Malvoz** [comment]
I don't think this is a concern anymore, as soon as browsers catch up to implement `rel="noopener"` by default. This was changed in https://github.com/whatwg/html/pull/4330/files

**Comment by annevk** [comment]
Yeah, COOP or consistently using target=_blank are the way to go here.

**Comment by kdzwinel** [comment]
@andypaicu @Malvoz @annevk  thanks a lot!

Making sure that all links are `target=_blank` is not much different from the existing situation where we have to make sure that all links are `rel=noopener`, so this doesn't really solve the issue described here.

COOP looks great though! (although I expect that some people may find it to be too strict because it also affects iframes)

**Comment by annevk** [comment]
It should not affect iframes. https://gist.github.com/annevk/6f2dd8c79c77123f39797f6bdac43f3e has a more formal definition.

**Comment by kdzwinel** [comment]
Thank you for that summary @annevk! It's way more approachable than https://github.com/whatwg/html/issues/3740 with its 80+ comments 😉

**Comment by annevk** [comment]
Even more accessible would be https://docs.google.com/document/d/1zDlfvfTJ_9e8Jdc8ehuV4zMEu9ySMCiTGMS9y0GU92k/edit. As it's not all quite ready yet none of this has been widely publicized yet, but we appreciate review.
