### ISSUE TITLE
CSP policy is visible in response header

### ISSUE THREAD

**Issue by ashok003** [w3c/webappsec-csp#317]
Hi Team, 

It may not be a code related issue but an observation. What ever CSP policy I set, it is returned as a response header to the user. This information can be accessed in browser tools. So if the user is malicious, he have information about all the whitelisted domains for script, style, frame etc., he knows if the website allows inline-style or inline script. I believe he can abuse this information and frame an attack accordingly. 
I feel the CSP header should not be visible in browser tools and CSP policy should be hidden to end user
Thanks

**Comment by ScottHelme** [comment]
The information is sent to the client and thus can't be protected from the client.

**Comment by dveditz** [comment]
Even without a CSP being transmitted you can use modern browser tools or old-style MITM proxies to see what resources a web page loads. There is no way for the server to communicate a policy to the browser without the user being able to  discover or intercept it. The browser is the "User Agent" -- literally the user's agent -- and can't (and won't) keep secrets from the user.
