### ISSUE TITLE
Matching schemeless expressions

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#34]
In https://w3c.github.io/webappsec-csp/#match-url-to-source-expression, section 
> If expression does not have a scheme-part, then return "Does Not Match" unless one of the following conditions is met:
>
>    origin's scheme is url's scheme
>
>    origin's scheme is "http", and url's scheme one of "https", "ws", or "wss".
>
>    origin's scheme is "https", and url's scheme is "wss".

looks incorrect to me, as it implies that `url` would match solely based on the **schemes** of `url` and `origin`
I think it is missing explicit statement that the rest -parts should match. If that's what you meant, I can try to fix this.

**Comment by mikewest** [comment]
Hrm. Reading it, I do think it's correct.

The step returns "Do Not Match" unless one of those conditions is met. That is, those conditions are necessary but not sufficient to return "Matches". The remaining steps are still executed.

**Comment by shekyan** [comment]
Oh. My bad, you are right.
There is numbering issue in the source, which is overwritten during generation, but would be nice to fix: https://github.com/w3c/webappsec-csp/blob/master/index.src.html#L1874 should say 3 and so on.

**Comment by mikewest** [comment]
Happy to accept a patch to fix it! :)

**Comment by shekyan** [comment]
https://github.com/w3c/webappsec-csp/pull/38
