### ISSUE TITLE
Consider enforcing default-src if not explicit

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#35]
In CSP3, source expression set of `default-src` is null if not explicitly present.

>6.1.10.5. Get the effective source list for request and policy
>
>If the effective directive for a request is not present in a policy, fetch directives will fall back to using the >value of default-src, if present. The effective source list
>for a request (request) and policy (policy) is therefore determined by the following algorithm:
>
>   1.Let effective be the result of executing §6.1.10.4 Get the effective directive for request on request.
>
>    2.If effective is null, return null.
>
>    3.If a directive whose name is effective is present in policy's directive set, return that directive’s value.
>
>    4.If a directive whose name is default-src is present in policy's directive set, return that directive’s value.
>
>    5.Return null.

Firstly, I believe step 2 needs to be removed because steps 3-5 would not be reached in the case that effective directive is not `default-src`.

Secondly, consider replacing 5 with something more restrictive. I would recommend one of 'none' or 'self' as a new default.

**Comment by mikewest** [comment]
> I believe step 2 needs to be removed ...

I agree that it doesn't change the output of the algorithm, but I do think it's worth keeping for reasons of clarity.

> Secondly, consider replacing 5 with something more restrictive

We've chosen not to do that because of the various directives that don't imply restrictions to fetches. For instance, `Content-Security-Policy: sandbox;` shouldn't mean that no resources can be loaded.

**Comment by dveditz** [comment]
Firefox used to have this behavior -- if default-src was not specified it was enforced as "default-src 'none';".  This had compatibility problems when IE introduced the sandbox directive (and supported no others). Sites specifying the sandbox for added protection didn't think to add the ignored-by-IE default-src * directive, and those pages broke horribly in Firefox. The CSP3 language replicates the effect of what was eventually standardized in CSP1 and CSP2 using different language.

Now that we've added several other directives orthogonal to sub-resource loads we should not now change this. Mike: can we close this issue?

**Comment by mikewest** [comment]
Yup. We've refactored things quite a bit since this was filed, and I think part 1 ends up being obsolete, while part 2 is something we're still not planning on changing.
