### ISSUE TITLE
Should CSPEE be its own repository?

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-csp#352]
It'd be nice to track issues and such separately and not have a joined commit history.

**Comment by mikewest** [comment]
At this point, yes. Earlier, it required a lot of refactoring changes in CSP as well, and doing those in a single commit made a lot of sense.

@wseltzer: Would you be able to create a distinct repository for this spec (`webappsec-cspee`)? If so, I'll move it over.

**Comment by wseltzer** [comment]
So created!

**Comment by mikewest** [comment]
Populated https://github.com/w3c/webappsec-cspee with w3c/webappsec-csp@0e11091019856f6a4e2deba233787e7822c289d7. Redirecting from https://w3c.github.io/webappsec-csp/embedded/ to https://w3c.github.io/webappsec-cspee/. I don't think there's an easy way to move issues, but I'll find the migration script we used when we pulled things off of w3c/webappsec in the first place.
