### ISSUE TITLE
URL and semicolon clarity

### ISSUE THREAD

**Issue by Nick-Levinson** [w3c/webappsec-csp#36]
A URL may legally include a trailing semicolon, even though that's unusual. In a CSP, the last token is followed by a semicolon. Therefore, for clarity of authoring, editing, and parsing, an author should space-separate a single or last URL and the semicolon that closes a directive's value and the specification should support that.

**Comment by michaelficarra** [comment]
@Nick-Levinson Can you link to an authoritative source to verify the claim that

> A URL may legally include a trailing semicolon, even though that's unusual.

and quote the relevant text here?

**Comment by hillbrad** [comment]
I believe this is covered by the note here:
http://www.w3.org/TR/CSP2/#source-list-parsing

Because CSP policies are parsed by strictly splitting on the ; literal, you
MUST percent-encode it if it appears in a URL.  (and it is a legal URL
character)

**Comment by hillbrad** [comment]
The behavior observed in most web browsers is the following:

https://url.spec.whatwg.org/#url-code-points

RFC 3986 differs from established user agent practice in a number of
places.  In particular, I'm not aware that ; was ever 'officially' reserved
as a sub-delimiter for http/https schemed URLs. (and even then, it is still
a valid character, just one that should be encoded to avoid conflicts when
it is actually being used as a delimiter)

It is, in point of fact, used all over the place on the web as an unencoded
character.  It was recommended and widely adopted for cookie-less "session
rewriting" with additional path info by early editions of the O'Reilly Java
Servlet book, and it is currently used by some CDNs.  One might argue these
are informal sub-delimiter use cases and should not appear in a CSP source
expression, but no browser implementations are really stopping them from
being used in any way that any site chooses.

**Comment by michaelficarra** [comment]
CSP allows only URLs as specified by RFC 3986. It does not permit anything permitted by "established user agent practice". See [section 4.2](http://www.w3.org/TR/CSP/#source-list-syntax), particularly the definition of `path-part`.

**Comment by hillbrad** [comment]
3986 says:

"If data for a URI component would conflict with a reserved character's
purpose as a delimiter, then the conflicting data must be percent-encoded
before the URI is formed."

Which is the behavior that CSP specifies in the note - it is reserved as a
delimiter for the purpose of use in a CSP source expression so it must be
encoded.

However, in general, for http and https URLs as dereferenced by a browser,
a semicolon has no special meaning and is allowed to be present, unencoded,
as a character in the URL.  So if you are starting with a URL that is
generally acceptable to browsers which contains a character which otherwise
has no significance with regards to dereferencing behavior, you should
observe the caveat in the note when placing it in this new context.

**Comment by michaelficarra** [comment]
The same could be said for the space character; `source-expression`s are delimited by spaces, so spaces need to be percent-encoded in that context, but spaces could very well appear literally in a URL in various user agent contexts. I don't think there's any change we should make to the CSP spec here.

**Comment by hillbrad** [comment]
Agreed, no changes necessary.  It is clear that a policy is parsed by strictly splitting on ; and any time it appears in a URL it must be % encoded.

**Comment by Nick-Levinson** [comment]
I think the role of reserved characters in a URI is misapplied here. In RFC 3986, they're reserved to prevent conflicts within a URI, such as if a parameter and its value are part of a URL. They're relevant to certain kinds of URI components, so if such a component is absent then reserving or percent-encoding the character is unnecessary. I have just successfully named a folder on my OpenSuse 13.2 Linux laptop "a;b", successfully saved a file into it, and opened the file from it, so presumably http://example.com/a;b/test-ab.txt would be a valid path without percent-encoding. Percent-encoding is recommended ("should") in section 2.2; it is not required.

I don't recall seeing a space in a URL other than in a browser's address bar, but I think going to that URL or copying it out of there into a text file makes it spaceless. I recall seeing equals signs and slashes and colons many times in URLs, the latter two when a URL is embedded within another URL (very often percent-encoded but somewhat often not) and the colon also to indicate a port with a domain, and hash marks are turning up besides being used as fragment identifiers (I think it also has to do with Ajax and looks like a trailing directory name). Question marks are widely used without percent-encoding as query indicators (e.g., https://www.google.com/search?q=Mars&ie=utf-8&oe=utf-8).

RFC 3986 Appx C says, "it is important to be able to delimit the URI . . . from punctuation marks that might be mistaken for part of the URI." It goes on to describe common practice and recommendations, but not requirements, and the delimiters it supports are angle brackets, straight double quotation marks, and whitespace, not other punctuation marks.

At any rate, most people writing a CSP with a URL will not think to go to the trouble of percent-encoding what is not already percent-encoded. CSP level 2 sec. 4.2.1 requiring percent-encoding will likely often be missed or forgotten. How people usually behave is relevant.

I'm not online daily, so I missed the 16-hour window for replying. I hope this addresses the concerns and a solution can be found. Perhaps a parser should read from both directions, but I'm not expert enough to judge that possibility.

**Comment by hillbrad** [comment]
CSP2 is done, and there is no momentum for a breaking change like this now.
We even noticed this a long time ago (years) and the deployed base was
enough vs use of ; to not make the change then.  In CSP3 we may explore
different policy syntax and should take this into consideration if we do.
