### ISSUE TITLE
Using active document of a browsing context introduces a security vulnerability

### ISSUE THREAD

**Issue by andypaicu** [w3c/webappsec-csp#360]
Instances of using the active document of a browsing context introduce a vulnerability where the browsing context could have navigated in the middle of the current request and we are inheriting a new document's CSP.

Better explained by @bzbarsky here: https://github.com/w3c/webappsec-csp/pull/358#issuecomment-435405253

We should use the request's [client](https://fetch.spec.whatwg.org/#concept-request-client).

Places that do this (incorrectly):
https://w3c.github.io/webappsec-csp/#initialize-document-csp
https://w3c.github.io/webappsec-csp/#should-block-navigation-request
https://w3c.github.io/webappsec-csp/#should-block-navigation-response

Places where the usage is correct and should be kept:
https://w3c.github.io/webappsec-csp/#frame-ancestors-navigation-response

**Comment by bzbarsky** [comment]
It's not clear to me that the use in https://w3c.github.io/webappsec-csp/#frame-ancestors-navigation-response is correct either, fwiw.   "parent’s active document" might not be the same as the document that contained the iframe tag that created the "current" (well, the old value, before we set it to "parent") browsing context.

**Comment by bzbarsky** [comment]
> so using the request is definitely wrong

Sure.

> If the parent of an iframe navigates away doesn't the iframe loading stop anyway?

Probably yes, but I would be happier if we did not rely on that.   For example,  if preloading ever gets resurrected, this would become a problem again.

> Is there a way to change the parent document but keep a child iframe?

In general, sure, though not necessarily while there is a child request running in the iframe.  Both Firefox and Safari implement,  and the spec supports, mechanisms that store the whole DOM/JS state in the session history.

Anyway, I think what would make the most sense for frame-ancestors is an algorithm like this:

1. Let _current_ be _target_.
1. While _current_ is a [nested browsing context](https://html.spec.whatwg.org/multipage/browsers.html#nested-browsing-context):
   1. Let _document_ be the Document that _current_ is [nested through](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-nested-through).
   1. Let _origin_ be the result of executing the URL parser on the ASCII serialization of _document_'s origin.  (No need to indirect via the settings object, afaict... but if there is, it would be good to have a note explaining why that's needed.)
   1. Do the check on _origin_.
   1. Set _current_ to _document_'s browsing context.
