### ISSUE TITLE
CSP 3 draft does not conform to the HTTP/1.1 standard for headers

### ISSUE THREAD

**Issue by markushausammann** [w3c/webappsec-csp#361]
Editor’s Draft, 5 November 2018 offers a wrong approach to duplicate headers.

https://w3c.github.io/webappsec-csp/#multiple-policies

According to HTTP/1.1 specs it is not allowed to send duplicate headers to a client when it's values are not comma separated. The examples given in this chapter violate this rule.

**Comment by mikewest** [comment]
Not being allowed to send multiple headers doesn't mean that servers _don't_ send multiple headers. The spec defines what to do in the case that multiple headers show up, despite the spec's exhortations to the contrary. :)

What would you like to see change in the spec?

**Comment by markushausammann** [comment]
Ok, I get that. But for some reason the spec makes people (or just me?) think that multiple headers are something that is normal in the CSP context. It would be good to state more clearly that only ever one CSP header is expected and applications have to take care of union merging several policies.

**Comment by mikewest** [comment]
In https://w3c.github.io/webappsec-csp/#csp-header, the document does say that "A server SHOULD NOT send more than one HTTP response header field named "Content-Security-Policy" with a given resource representation."

Is there something else we could add to make this suggestion clearer?

**Comment by markushausammann** [comment]
Here's my understanding of the situation.

It should say: A server SHOULD NOT send more than one HTTP response header field named "Content-Security-Policy". (<- full stop)
Then add: NB! Given the current developments, you're well advised to read this as "MUST NOT".
The part with "with a given resource representation" is not correct.

Then you should probably correct your examples, they are a MUST NOT:

```
Content-Security-Policy: default-src 'self' example.com example.net; 
connect-src 'none';
```

They are neither key=value or value, value, ... which would be the only way anythingthing like this would be allowed with the "SHOULD NOT" clause.

**Comment by JannisBush** [comment]
> Rather than changing the spec to be more forceful about avoiding this, can we instead update it so that this behavior is officially supported? (Or, if this is fundamentally at odds with HTTP, what else could we do to allow setting several policies as separate headers?)

According to my understanding sending multiple CSP headers is okay according to the HTTP spec.
> This means that, aside from the well-known exception noted below, a sender MUST NOT generate multiple field lines with the same name in a message (whether in the headers or trailers) or append a field line when a field line of the same name already exists in the message, unless that field's definition allows multiple field line values to be recombined as a comma-separated list (i.e., at least one alternative of the field's definition allows a comma-separated list, such as an ABNF rule of #(values) defined in [Section 5.6.1](https://www.rfc-editor.org/rfc/rfc9110#abnf.extension)). (https://www.rfc-editor.org/rfc/rfc9110#section-5.3)

As the CSP header is defined as `Content-Security-Policy = 1#serialized-policy`(https://w3c.github.io/webappsec-csp/#csp-header), HTTP allows sending multiple CSP headers.

---
Instead of removing the example with multiple CSP headers, I would suggest to remove the following sentence from the specification:
> A server SHOULD NOT send more than one HTTP response header field named "Content-Security-Policy" with a given [resource representation](https://tools.ietf.org/html/rfc7231#section-3).`

Sending multiple CSPs is [best practice](https://static.sched.com/hosted_files/locomocosec2019/db/CSP%20-%20A%20Successful%20Mess%20Between%20Hardening%20and%20Mitigation%20(1).pdf#page=44) as certain policies such as `script-src 'self', script-src 'nonce-abc'` can only be achieved with multiple CSPs.
Only (implicitly) recommending doing so via one header with a comma while explicitly discouraging  multiple headers (https://github.com/w3c/webappsec-csp/issues/216#issuecomment-301275252) is confusing and might hinder the adoption of such best practice CSPs.

**Comment by annevk** [comment]
@JannisBush would you be interested in writing a PR? I tend to agree that this makes no sense.

**Comment by JannisBush** [comment]
@annevk 
I can create a pull request.
I would just replace the above sentence with:
> A server MAY send more than one HTTP response header field named "Content-Security-Policy" with a given [resource representation](https://tools.ietf.org/html/rfc7231#section-3).`

How such responses are processed and why it might make sense is already specified elsewhere in the document (https://w3c.github.io/webappsec-csp/#multiple-policies).

**Comment by annevk** [comment]
Removing it completely would also be fine I think. It already follows from the comma syntax.

**Comment by mikewest** [comment]
I think Anne's right that just dropping the sentence would be fine. If you wanted to find some way to work https://www.rfc-editor.org/rfc/rfc9110.html#section-5.2 into a note, go for it, but I agree that the behavior falls out of the syntax in the way that section and the following define.

**Comment by annevk** [comment]
Fixed by https://github.com/w3c/webappsec-csp/commit/b05cfac6c286e33c3c275dc652083db1eda8667c.
