### ISSUE TITLE
Bug in directive-value grammar

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#366]
Looks like there is a bug in directive-value grammar:

[directive-value](https://w3c.github.io/webappsec-csp/#grammardef-directive-value) grammar says that it can contain no characters, while detailed grammar for, for example any fetch directive, doesn't allow no characters for [serialized-source-list](https://w3c.github.io/webappsec-csp/#grammardef-serialized-source-list).

**Comment by mikewest** [comment]
> directive-value grammar says that it can contain no characters, 

By "no characters", do you mean an empty value? I think it's true that `script-src;` would be malformed, while `block-all-mixed-content;` wouldn't. Is that what you're referring to?

**Comment by shekyan** [comment]
Yes, that's what I mean.

**Comment by mikewest** [comment]
Ok. It seems expected to me that `script-src` would not accept an empty value, while `sandbox` would. Given that, what would you like the spec to say?

**Comment by shekyan** [comment]
I expect that `serialized-source-list`,  `ancestor-source-list`, `media-type-list`, grammar would allow empty string, just like grammar for `sandbox`, for example. I can sketch a PR if you are ok with this approach.

**Comment by mikewest** [comment]
Why is it good for `script-src;` to be valid? It seems reasonable to consider it invalid to me?

**Comment by michaelficarra** [comment]
@mikewest That would be semantically treated as `script-src 'none'` which I think is a reasonable shorthand. The mental model would be "zero or more source expressions" instead of the current "one or more".

**Comment by mikewest** [comment]
Why is it better to allow `script-src;` than to require `script-src 'none'`? I mean, sure, we could totally do it: does it solve an actual problem? Are people doing this in the wild today, and feeling bad about themselves, and wish that the thing they were doing was valid?

**Comment by michaelficarra** [comment]
Well I've tested in Chrome and Firefox at least, and this is already how they work. It's a pretty obvious extension. But for non-fetch directives like `plugin-types`, there's no equivalent to the `'none'` source-expression, so this would actually be giving website authors more power.

**Comment by andypaicu** [comment]
I think providing a `'none'` equivalent to `plugin-types` is reasonable. I don't see any other directive that is missing the `'none'` equivalent (at least specifically in this spec, and I can't think of any other directive in other specs that need it).

I agree with @mikewest that I don't see much value in making `script-src;` mean the same thing as `script-src 'none'` and I can imagine it might lead to confusion.
