### ISSUE TITLE
Broken references in "Integration with Fetch" section

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec-csp#367]
https://w3c.github.io/webappsec-csp/#fetch-integration says:

> §4.1.3 Should request be blocked by Content Security Policy? is called as part of step #5 of its Main Fetch algorithm.

but step 5 of that algorithm has nothing to do with CSP.

> §4.1.4 Should response to request be blocked by Content Security Policy? is called as part of step #13 of its Main Fetch algorithm.

and again that has nothing to do with CSP.

As an editorial matter, "of its" is unclear to me: what is "it" referring to there?

**Comment by andypaicu** [comment]
Thank you for reporting this. I've updated the references.
