### ISSUE TITLE
Make CSP inheritance for javascript: more explicit

### ISSUE THREAD

**Issue by ckerschb** [w3c/webappsec-csp#368]
Currently javascript: inherits the CSP (there is also a web platform test for that [1]). Within the specification however [2], we only link to local schemes [3], which states:
> A local scheme is a scheme that is "about", "blob", "data", or "filesystem". 

So the javascript: is not mentioned, we should make that more explicit.

[1] https://github.com/web-platform-tests/wpt/blob/master/content-security-policy/inheritance/iframe.html#L75
[2] https://w3c.github.io/webappsec-csp/#initialize-document-csp
[3] https://fetch.spec.whatwg.org/#local-scheme

**Comment by mikewest** [comment]
This probably needs to happen in step ~13 of https://html.spec.whatwg.org/#javascript-protocol. @annevk, WDYT?

**Comment by mikewest** [comment]
I wonder if it would make sense to set `response`'s URL in that step to be `about:blank`, as I hope that would just do the right thing in https://html.spec.whatwg.org/#initialise-the-document-object?

**Comment by annevk** [comment]
Long term we really need to have some way of creating a document with inherited state and make sure that's used in all the right places. That way we don't have this endless list of exceptions to deal with whenever we add new state to documents.

I'm not sure if `about:blank` works here, is that the URL the document ends up having?

**Comment by mikewest** [comment]
> Long term we really need to have some way of creating a document with inherited state and make sure that's used in all the right places. That way we don't have this endless list of exceptions to deal with whenever we add new state to documents.

:+1: 

> I'm not sure if `about:blank` works here, is that the URL the document ends up having?

That's the URL that we end up with in Chrome. It's somewhat unclear from the spec, but it seems reasonable to assume that navigating to a response with an empty URL list would end up as a navigation to `about:blank`.

**Comment by annevk** [comment]
How do you explain inner `<a>` of `<a href="javascript:'<a href=/test>test</a>'">test</a>` resolving against outer `<a>`'s node document's base URL then?

**Comment by annevk** [comment]
`<a href="javascript:'<script>alert(document.URL)</script>'">test</a>` also yields `<a>`'s node document's URL.

**Comment by andypaicu** [comment]
From my point of view it would be both easier and clearer if we specified `javascript:`. Otherwise if we do something like setting the url to `about:blank` we would still need to make a note of the fact to make it clear the same way we do with `srcdoc`.

**Comment by mikewest** [comment]
> How do you explain inner `<a>` of `<a href="javascript:'<a href=/test>test</a>'">test</a>` resolving against outer `<a>`'s node document's base URL then?

:scream:

> `<a href="javascript:'<script>alert(document.URL)</script>'">test</a>` also yields `<a>`'s node document's URL.

Firefox and Chrome diverge here, FWIW, reporting `javascript:...` and `about:blank` respectively (see https://mikewest.github.io/bug-test-scratchpad/iframe-javascript.html). They do agree on `window.origin`, which is nice.

**Comment by annevk** [comment]
Note that `<iframe src>` is apparently different from `<a href>` in Chrome, because with that I get the referring document's URL as I stated. In Firefox it's `javascript:...` though, so maybe there's room for consistency.

**Comment by bzbarsky** [comment]
> In Firefox it's javascript:... though

Note that this is not what the spec says, and has been causing compat issues of various sorts.  We plan to switch to the specced behavior here; I just need to finish up those patches.
