### ISSUE TITLE
Evaluate service-workers mode for CSP violation reports

### ISSUE THREAD

**Issue by cvazac** [w3c/webappsec-csp#383]
Step 3.4.2.3 [here](https://w3c.github.io/webappsec-csp/#report-violation) omits the [`service-workers mode`](https://fetch.spec.whatwg.org/#request-service-workers-mode) enum, which defaults to `"all"`.

Do we want this?

I ask because I'm seeing discrepant behavior amongst user agents. Service workers in Chrome and Firefox can see those reports, but not so in Safari. 

I argue that we *do* want those requests exposed to service worker, with the following use cases in mind:
1) strip out private data before it goes out (alternate to https://github.com/w3c/webappsec-csp/issues/111)
2) if we detect no network, save the POST for later
3) batch requests together before sending out to network

**Comment by wanderview** [comment]
The default value for `service-workers mode` is "all":

https://fetch.spec.whatwg.org/#request-service-workers-mode

So I agree with you.  Can you file a webkit bug?

**Comment by cvazac** [comment]
filed: https://bugs.webkit.org/show_bug.cgi?id=194392
