### ISSUE TITLE
Null references in specification

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#39]
Define what `null` is for every distinct context in the specification, or use "empty" instead.

For example, 

```
If url's host is null, return "Does Not Match".
```

might be confusing.

**Comment by michaelficarra** [comment]
I prefer the word "missing".

**Comment by mikewest** [comment]
I've gone through the occurrences of `null` in the document, and I think they're consistent. I recognize that reasonable folks can disagree about what word to use for this case; unless there's a compelling reason to change things, I'd prefer to keep the existing verbiage. :)
