### ISSUE TITLE
Please clarify which text encoding should be used to compute the hash value of inline script/style

### ISSUE THREAD

**Issue by duanyao** [w3c/webappsec-csp#40]
When I read [CSP2 spec](http://www.w3.org/TR/CSP/), it is not clear which text encoding should be used to compute the hash value of inline script/style. Is it the original encoding of the HTML page? Is it UTF-8 or UTF-16LE/BE?

One example in the spec (" SHA-256 digest of alert('Hello, world.'); is qznLcsROx4GACP2dm0UCKCzCG+HiZ1guq6ZZDob/Tng=") implies the encoding is ASCII-compaitable, so I guess UTF-8 should be used?

**Comment by duanyao** [comment]
I'm not sure I understand the modification correctly. Does it mean the SHA-256 hash of the `<script>` in the following html file

```html
<meta charset="GBK" >
<script>var 啊 = 0</script>
```

is computed as
```js
base64(hash_SHA256(encode_GBK(document.getElementsByTagName('script')[0].textContent)))
```

**Comment by mikewest** [comment]
Ah. You're right. I didn't do a good job explaining what's going on. The page's encoding only effects the parser. By the time we get to the point of making checks against attribute values or element contents, we're using unicode code points.

Chrome suggests that `sha256-aKlRhN3egl14eKdmrXqulCr572ZlgNoSn8+go79mwQM=` would be appropriate for that case. Firefox agrees. As does `echo -n "var 啊 = 0" | openssl dgst -sha256 -binary | openssl enc -base64` in a UTF-8 terminal window.
