### ISSUE TITLE
CSP domain.com vs domain.com/ with slash

### ISSUE THREAD

**Issue by laukstein** [w3c/webappsec-csp#403]
I have noticed some using in CSP a domain name with and some without slash `/` in the end of a domain, like

    Content-Security-Policy: default-src 'none'; script-src https://www.google-analytics.com

and

    Content-Security-Policy: default-src 'none'; script-src https://www.google-analytics.com/

Is there any difference when speaking only about a domain (may contain a protocol, doesn't have path or filename)? Which one is preferred one?

Personally I think both expected to behavior the same and end slash is unnecessary.
BTW I have noticed canonical URLs requiring slash in end like `https://www.google-analytics.com/` (I think Lighthouse and other tools otherwise shows an error).

Please mention this also in spec so that everyone can fallow same "recommended concept".

**Comment by dveditz** [comment]
This issue does not describe a problem or change request for the spec (tutorial or instructional material doesn't fit). Please use our mailing list for discussions as described in the spec:

> The (archived) public mailing list public-webappsec@w3.org (see instructions) is preferred for discussion of this specification. When sending e-mail, please put the text “csp3” in the subject, preferably like this: “[csp3] …summary of comment…”

**Comment by laukstein** [comment]
@dveditz, please ReOpen this issue. Spec is missing details explaining if and how `domain.com vs domain.com/` differently affects in CSP.

**Comment by annevk** [comment]
It makes no difference per my reading of https://w3c.github.io/webappsec-csp/#match-url-to-source-expression.

**Comment by laukstein** [comment]
@annevk, then likely the documentation is wrong. I have noticed that `https://domain.com` will allow  requests for/by all under domain domain.com with protocol HTTPS (like https://domain.com/foo/bar/file.name?query=value), while `https://domain.com/` will allow requests only in first path level like https://domain.com/file.name?query=value . Please correct me if I'm wrong.

**Comment by annevk** [comment]
Actually, you may be right given https://w3c.github.io/webappsec-csp/#path-part-match.

**Comment by laukstein** [comment]
@annevk, @dveditz
See, it is not clear in any documentation, even isn't 100% clear for us how it expected to behavior. Please reopen this issue and fix it, making things clear.
