### ISSUE TITLE
CSP HTTP headers not registered with IANA

### ISSUE THREAD

**Issue by SmashManiac** [w3c/webappsec-csp#404]
The `Content-Security-Policy` and `Content-Security-Policy-Report-Only` HTTP headers are missing from the [IANA Permanent Message Header Field Names registry](https://www.iana.org/assignments/message-headers/message-headers.xhtml#perm-headers).

Not sure how this was missed for all these years, especially when considering that the [IANA Content Security Policy Directives registry](https://www.iana.org/assignments/content-security-policy-directives/content-security-policy-directives.xhtml#directives) was created more than 3 years ago by [RFC 7762](https://tools.ietf.org/html/rfc7762).

**Comment by Malvoz** [comment]
FWIW this was mentioned in https://github.com/w3c/webappsec/issues/532 with no feedback.

**Comment by mikewest** [comment]
@wseltzer, @samuelweiler: Is this something y'all can take care of? If not, I'll figure out the right list to send emails to. :)

**Comment by clelland** [comment]
This can be done by email to ietf-message-headers@lists.ietf.org, per [RFC](https://tools.ietf.org/html/rfc3864), FYI

(Just looking into this for [Feature-Policy](https://github.com/w3c/webappsec-feature-policy/issues/331) as well)

**Comment by SmashManiac** [comment]
The registry has moved to [Hypertext Transfer Protocol (HTTP) Field Name Registry](https://www.iana.org/assignments/http-fields/http-fields.xhtml).

Can someone at the W3C take ownership of this? I don't think I can do the submission myself, and this issue has been pending for more than 2 years even though it should have been a trivial matter.

**Comment by SmashManiac** [comment]
@mnot Ping! 10 days has passed and CSP headers are still not published.

**Comment by mnot** [comment]
It's now active. Please make a request over at https://github.com/protocol-registries/http-fields and we'll get it done.

**Comment by SmashManiac** [comment]
@mikewest As an outsider, I'm not 100% sure which URL is authoritative for the specification document(s), and it sounds like you have other missing headers in mind. Can you do the follow-up using the instructions @mnot provided?

**Comment by mikewest** [comment]
Filed https://github.com/protocol-registries/http-fields/issues/14 and https://github.com/protocol-registries/http-fields/issues/15.

**Comment by mikewest** [comment]
https://www.iana.org/assignments/http-fields/http-fields.xhtml#:~:text=%5BRFC4229%5D-,Content-Security-Policy,-permanent

🥳
