### ISSUE TITLE
Consider enforcing default port if expression matches only scheme-source grammar

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#41]
Expression matching algorithm tells us that expression without `port-part` should match a url with _default for scheme_ port only:

> If expression does not contain a port-part, and url’s port is not the default port for url’s scheme, return "Does Not Match".

Consider making  `scheme-source` _expression_  matching stricter by matching only [default ports](https://url.spec.whatwg.org/#default-port) . 

E.g. 
`
script-src https:;
`
should match `https://example.com` but should _not_ match `https://example.com:8443`

Also, [default port](https://url.spec.whatwg.org/#default-port) is defined only for [special schemes](https://url.spec.whatwg.org/#default-port), meaning we have undefined behavior if scheme is not a special scheme.

**Comment by shekyan** [comment]
It took me 5 minutes to understand what I meant here, so I rephrased the issue, my apologies. 

Still, I think this should be considered.

**Comment by mikewest** [comment]
I don't think this is a good idea; we've already put developers through a good deal of churn for very little benefit with a number of other tightening mechanisms, and I think the incremental value here is way too low to justify even more churn.
