### ISSUE TITLE
hash-algo

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-csp#418]
> If directive’s value does not contain a source expression whose hash-algorithm is a case-sensitive match for source’s hash-algo component

Should that be hash-algorithm? It's the only instance of hash-algo in this document (despite SRI referencing CSP for hash-algo).

**Comment by sideshowbarker** [comment]
The discrepancy here seems to just be a stray carry-over from the CSP2 spec that didn’t get caught and changed when the rewrite was done to produce CSP3.

Specifically, the CSP2 spec defined a `hash-algo` production rather a `hash-algorithm` production. And the CSP2 definition of the `hash-algo` production is exactly the same as the CSP3 definition of the `hash-algorithm` production:

- https://www.w3.org/TR/CSP2/#hash_algo
- https://w3c.github.io/webappsec-csp/#grammardef-hash-algorithm

So it seems clear the discrepancy was just an oversight. I’ll raise a PR.

**Comment by sideshowbarker** [comment]
Incidentally, I notice this part of the spec says that a case-*sensitive* match of hash-algorithm values must be performed.

That seems intuitively wrong and not consistent with observed implementation behavior in that, e.g., `SHA512` in a CSP hash-source would not be considered a match for `sha512`.

And at https://www.w3.org/TR/CSP2/#source-list-valid-hashes the corresponding part of the CSP2 spec says a case-*insensitive* match must be performed — so as far as I can see, conforming to that part of the CSP3 spec as written would require implementations to change their behavior in a backward-incompatible way.

Given that, it seems most likely that case-*sensitive* requirement in the CSP3 is an oversight — so I’ll change that too, in the same PR I raise for the `hash-algo`/`hash-algorithm` discrepancy.
