### ISSUE TITLE
Use Infra for JSON

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-csp#455]
In particular for serialization this should probably use https://infra.spec.whatwg.org/#serialize-an-infra-value-to-json-bytes.

**Comment by sideshowbarker** [comment]
I’ll make some time to work on this.

**Comment by sideshowbarker** [comment]
> In particular for serialization this should probably use [infra.spec.whatwg.org/#serialize-an-infra-value-to-json-bytes](https://infra.spec.whatwg.org/#serialize-an-infra-value-to-json-bytes).

To be clear about something: Even though the relevant algorithm at https://w3c.github.io/webappsec-csp/#deprecated-serialize-violation currently has this:

> Return the result of executing JSON.stringify() on object.

…and `JSON.stringify()` returns a string – not bytes — the reason we don’t want to replace that with  [infra.spec.whatwg.org/#serialize-an-infra-value-to-a-json-string](https://infra.spec.whatwg.org/#serialize-an-infra-value-to-a-json-string) (string) but instead with [infra.spec.whatwg.org/#serialize-an-infra-value-to-json-bytes](https://infra.spec.whatwg.org/#serialize-an-infra-value-to-json-bytes) (bytes) is that it ends up being passed to the Fetch request algorithm as the request *body*, and the request *body* is defined as being a byte sequence.

Right?

**Comment by annevk** [comment]
Yeah, I'm not sure I had considered that when filing, but that seems right.
