### ISSUE TITLE
Specify sanitizing algorithm of blockedURL, documentURL, sourceFile beyond fragment exclusion

### ISSUE THREAD

**Issue by Rob--W** [w3c/webappsec-csp#489]
When a CSP violation report is generated, the current spec text specifies that the URL minus the reference fragment should be reported, as shown below. I propose to (re-)introduce a section like the "strip uri for reporting" section from CSP2 (which disappeared from CSP3) that describes the algorithm that more closely matches the de facto behavior: The full URL minus reference fragment is only reported for http(s), ftp, ws(s). In other cases the scheme is reported instead.

References to implementation:

- Chrome: `StripURLForUseInReport` - https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/csp/content_security_policy.cc;l=864;drc=efb0f6367a11f87129195032753f332b925ecf5f
- Firefox: `StripURIForReporting` - https://searchfox.org/mozilla-central/rev/0b90e582d2f592a30713bafc55bfeb0e39e1a1fa/dom/security/nsCSPContext.cpp#935-963

More context and history is at https://bugzilla.mozilla.org/show_bug.cgi?id=1705523 . In there I added two wpt files to confirm this behavior with blob: and data:-URLs.

Current spec text:

> **documentURL**
> The result of executing the [URL serializer](https://url.spec.whatwg.org/#concept-url-serializer) on violation’s url, with the exclude fragment flag set.
> **referrer**
> The result of executing the [URL serializer](https://url.spec.whatwg.org/#concept-url-serializer) on violation’s referrer, with the exclude fragment flag set.
> **blockedURL**
> The result of executing the [URL serializer](https://url.spec.whatwg.org/#concept-url-serializer) on violation’s resource, with the exclude fragment flag set.
> **sourceFile**
> The result of executing the [URL serializer](https://url.spec.whatwg.org/#concept-url-serializer) on violation’s source file, with the exclude fragment flag set if the violation’s source file it not null and the empty string otherwise.

**Comment by ArthurSonzogni** [comment]
Thanks for opening this!

You [made](https://bugzilla.mozilla.org/show_bug.cgi?id=1705523) Firefox's behavior to converge toward Chrome, and today, I just [proposed](https://chromium-review.googlesource.com/c/chromium/src/+/3263879) changing Chrome behavior to help webpack users here: https://bugs.chromium.org/p/chromium/issues/detail?id=1264789.

I agree it would be nice indeed to agree on something to follow.  Do you have something in mind? Would you had comment on this [implementation](https://chromium-review.googlesource.com/c/chromium/src/+/3263879)?

**Comment by Rob--W** [comment]
> Thanks for opening this!
> 
> You [made](https://bugzilla.mozilla.org/show_bug.cgi?id=1705523) Firefox's behavior to converge toward Chrome, and today, I just [proposed](https://chromium-review.googlesource.com/c/chromium/src/+/3263879) changing Chrome behavior to help webpack users here: [crbug/1264789](https://bugs.chromium.org/p/chromium/issues/detail?id=1264789)
> 
> I agree it would be nice indeed to agree on something to follow. Do you have something in mind? Would you had comment on this [implementation](https://chromium-review.googlesource.com/c/chromium/src/+/3263879)?

I commented here: https://github.com/w3c/webappsec-csp/pull/527#issuecomment-971622969

**Comment by ArthurSonzogni** [comment]
Specification added in #527
