### ISSUE TITLE
Embedded: consider other contexts other than iframe

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#49]
It may be useful to apply embedded enforcement to other contexts like `<object>`, `<embed>`, may be even svg? 

I know for sure that one big company removed CSP from the web page that hosts swf files that are communicating to wherever. Those are third-party flash games, that are "randomly" picked on every page load. Sure they better load every swf in an iframe, but it'd be nice to have a CSP context directly on objects like that.

**Comment by mikewest** [comment]
It's a reasonable idea, but it would require Adobe to play ball and apply a policy to the SWF. Given the struggles I'm currently going through to get them to support simpler concepts like Mixed Content, I'm skeptical that we'd have much success.

**Comment by shekyan** [comment]
I guess mentioning `<object>` in [Policy Applicability](http://www.w3.org/TR/CSP2/#which-policy-applies) is also just a theory that is not implementable in near future?

**Comment by mikewest** [comment]
Well, we have control over the resource that the `<object>` includes. That is, we can block a request for an SWF itself.

The things that the SWF requests, however, are more complicated. Chrome can blanket ban requests and socket connections from a SWF, but we don't have any context for those requests. My understanding is that Firefox and other browsers can't block requests at all (as the SWF can just reach through the NPAPI framework into the underlying system calls).

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-cspee#4
