### ISSUE TITLE
Should navigational checks apply to javascript: navigations?

### ISSUE THREAD

**Issue by antosart** [w3c/webappsec-csp#491]
In the html spec, javascript: navigations do not go through "Should navigation request of type be blocked by Content Security Policy?" and should bypass CSP checks.

However, both chrome and firefox check CSP form-action on form-submissions (https://wpt.fyi/results/content-security-policy/form-action/form-action-src-javascript-blocked.sub.html?label=experimental&label=master&aligned)

**Comment by antosart** [comment]
Personally, since executing javascript URLs is governed by script-src, and it is a very special type of navigation, I would find it reasonable not to apply the navigational checks.

**Comment by dveditz** [comment]
Depends on whether you interpret "javascript: navigations" narrowly or broadly.  If a simple javascript: url doesn't return a string then no navigation takes place.  However, if the script that is run does something like `document.location = someURL;` then that action queues up a separate navigation request which _will_ be run through the CSP checks. So `script-src` governs the script-running part of a javascript URL, and any navigation "side-effects" are governed in the same way as any other script running on the page trying to navigate the document.

**Comment by annevk** [comment]
FWIW, I think if someone were to work through the `javascript:` URLs issues filed against the HTML Standard we'd come up with a reasonable answer here.

**Comment by antosart** [comment]
I was confused going through the html spec. I think there is a small bug: https://github.com/whatwg/html/pull/6626.

Nevertheless, I am wondering whether it makes sense to apply the normal navigational checks to javascript: URL. But since they are implemented, I guess we will leave them.
