### ISSUE TITLE
[embedded] Is the `csp` attribute policy applied recursively?

### ISSUE THREAD

**Issue by yoavweiss** [w3c/webappsec-csp#50]
In case that we have an `iframe` inside an `iframe`, will the policy defined by the main browsing context still be enforced on the internal nested browsing context?

I couldn't find a reference to that case in the spec (might've missed it) so wanted to make sure.

**Comment by shekyan** [comment]
I think http://www.w3.org/TR/CSP/#which-policy-applies is what you are looking for. Embedded context created by iframe should be controlled by the policy delivered with the iframe.

**Comment by jonathanKingston** [comment]
Pretty sure this was a discussion piece @mikewest wanted to open up to allow a parent policy to override. (I quickly searched for the discussion but couldn't find it).

Essentially if the UA permitted the main contexts CSP to restrict the child context it would modify the child contexts code execution which breaks SOP.
From my memory the direction of the conversation basically required that the child context to use a new special `Access-Control-Allow-...` header to permit the main context to do this.
I guess there could be a possibility that the main context could just completely block the whole child context if at any point in code execution it fails the CSP, I don't think however this solves the issue either.

Anyway it would be a nice discussion to have if possible?

**Comment by jonathanKingston** [comment]
Found it: https://github.com/w3c/webappsec-csp/issues/12

This is probably a duplicate of that.

**Comment by mikewest** [comment]
Right. Closing out in favor of embedded enforcement.

**Comment by mikewest** [comment]
(where this is addressed in https://w3c.github.io/webappsec-csp/embedded/#required-csp).
