### ISSUE TITLE
"null" disposition has no explanation

### ISSUE THREAD

**Issue by terriko** [w3c/webappsec-csp#53]
In Section 2.1 it says "Each policy has an associated disposition, which is one of null, "enforce", or "report". The value is null unless otherwise specified."

A quick glance doesn't turn up any explanation of what a "null" disposition implies, except in the parser.  Perhaps a sentence here would make things clearer for the reader?

**Comment by mikewest** [comment]
"`null`" throughout the document is more or less a placeholder for "This isn't set yet." I guess we don't actually need it in this case if we pipe the disposition through to the parsing logic...? I'll see what I can do about that.
