### ISSUE TITLE
match-source-expression appears to be missing from CSP2 and CSP3

### ISSUE THREAD

**Issue by 3lixy** [w3c/webappsec-csp#537]
I was looking for the match-source-expression on [CSP2](https://www.w3.org/TR/CSP2/) and [CSP3](https://www.w3.org/TR/CSP3/) but was not able to find it.

I can see match-source-expression on [CSP 1.1](https://www.w3.org/TR/CSP11/#match-source-expression). The specific point I was look for to see if it had changed in CSP2/3 was:

> If the source expression a consists of a single U+002A ASTERISK character (*), and url’s scheme is not one of blob, data, filesystem, then return does match.

Apologies if this has been answered already but could not spot it in previously raised issues.

**Comment by antosart** [comment]
I think what you are looking for is here https://www.w3.org/TR/CSP3/#match-url-to-source-expression

**Comment by 3lixy** [comment]
Must have missed that thanks. Looks to be here for CSP2 https://www.w3.org/TR/CSP2/#match-source-expression
