### ISSUE TITLE
“Report a violation” can seemingly reach “fire an event at” w/ WorkletGlobalScope

### ISSUE THREAD

**Issue by bathos** [w3c/webappsec-csp#545]
The value of a `WorkletGlobalScope.[[Realm]].[[HostDefined]]` environment settings object’s policy container’s CSP list is a [copy][1] of the (walking backwards now:) CSP list of the policy container of the ESO of the Realm Record of the Worklet whose global scopes list it’s being uniquely appended to.

Most CSP directives have no effect in a Worklet environment given they’re designed for narrow purposes that benefit from “stateless” execution at the browser’s discretion. There are no built-ins exposed that can kick off new fetches in them and a dynamic import expression will evaluate to an [immediately rejected Promise][2]. But:

1. The [`addModule`][3] algorithm hits [fetch a worker script graph][4]. A shared module graph with special fetch steps is shared by every WGS, but the fetch client settings object passed here is that of the WorkletGlobalScope. The steps from there are not exactly easy to follow, but as far as I can tell, you’re able to end up hitting [Should _request_ be blocked by Content Security Policy?][5] with the environment settings object of the WorkerGlobalScope in tow.
2. Unlike the dynamic import case, nothing special happens when Worklet code hits the HostEnsureCanCompileStrings host hook. If eval isn’t permitted by the CSP list, you’d end up in [EnsureCSPDoesNotBlockStringCompilation][6] as usual and the _realm_ will be `WorkletGlobalScope.[[Realm]]`.
3. If the Trusted Types & Dynamic Code Brand Checks proposals are implemented (as they are in Chromium) and if the CSP list is enforcing a Trusted Types policy, then even if eval is permitted, you’re guaranteed to bottom out early in the modified [EnsureCSPDoesNotBlockStringCompilation][7] if you use eval sinks because none of the Trusted Types API’s constructs’ exposure sets include Worklet. You just don’t got em!\*

For any of those paths we next end up in [Report a violation][8], where _target_ will be set to the WorkletGlobalScope at 3.2.  Then it wants to [Fire an event][9] at _target_ ... but it [isn’t an EventTarget][10] and _[undefined behavior]_ ensues.

Should probably go w/o saying, but especially in this case given there are some pretty byzantine/subtle inter-spec code paths involved, I could easily be missing something along the way. I’m also not sure whether, if I am correct, the remedy would be here or in HTML / Fetch / all three, but since this is where it’s most specifically relevant subject-wise it seems like the best starting point.

---

\* Though you could maybe narrow the CSP with trusted-types directives _after_ kicking off the worklet given the CSP list gets cloned? — i.e. it’s not a “live” connection to the original CSP list, it’s an instantiation-time snapshot. 🤔... and if I’m following this right, I think the original list is getting cloned for each new WGS instance. The browser is [supposed to be][11] able to do that at-will on or off the main thread unobservably. Given the original CSP list is mutable state of another realm / agent, there may be something off there.

[1]: https://html.spec.whatwg.org/multipage/origin.html#clone-a-policy-container
[2]: https://html.spec.whatwg.org/multipage/webappapis.html#hostimportmoduledynamically(referencingscriptormodule,-modulerequest,-promisecapability)
[3]: https://html.spec.whatwg.org/multipage/worklets.html#worklets-worklet:fetch-a-worklet-script-graph-2
[4]: https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-worklet-script-graph
[5]: https://w3c.github.io/webappsec-csp/#should-block-request
[6]: https://w3c.github.io/webappsec-csp/#can-compile-strings
[7]: https://w3c.github.io/webappsec-trusted-types/dist/spec/#csp-eval
[8]: https://w3c.github.io/webappsec-csp/#report-violation
[9]: https://dom.spec.whatwg.org/#concept-event-fire
[10]: https://html.spec.whatwg.org/multipage/worklets.html#workletglobalscope
[11]: https://html.spec.whatwg.org/multipage/worklets.html#dom-worklet-addmodule-dev:~:text=This%20allows%20the,safe%20programming%20techniques.

**Comment by antosart** [comment]
I am wondering. Should we fire the event on the parent document in the case of worklets?

**Comment by annevk** [comment]
Not in general as that creates a communication channel. It might be acceptable for audio worklets.

cc @domenic @padenot

**Comment by domenic** [comment]
The easy fix is just to have "report a violation" test if _target_ is an EventTarget. I suspect that is what implementations do?

**Comment by antosart** [comment]
The easy fix sounds fine. But then for the same reason we should also skip POSTing a violation (that's also a communication channel, since the violation is sent to the parent document's report-uri endpoint)?

**Comment by annevk** [comment]
Yeah I think so. Non-audio worklets are not supposed to be able to fetch.

**Comment by antosart** [comment]
I think this is fixed by #549.
