### ISSUE TITLE
"Get the effective directive for request" should handle at least worklets

### ISSUE THREAD

**Issue by evilpie** [w3c/webappsec-csp#554]
I am currently trying to map what the spec defines in https://w3c.github.io/webappsec-csp/#effective-directive-for-a-request to what Firefox implements at https://searchfox.org/mozilla-central/rev/3e1a721bce1da3ae04675539b39a4e95b25a046d/dom/security/nsCSPUtils.cpp#258. Sadly this includes a lot of internal stuff so kinda difficult to follow, but also not necessarily important for anyone else.

Anyway, I think there is at least one missing case. "audioworklet" and "paintworklet" should probably be treated as "script-src-elem".

**Comment by antosart** [comment]
I think you are correct. This is also tested in WPT: [here](https://wpt.fyi/results/content-security-policy/gen/top.meta/script-src-self/worklet-audio.https.html?label=master&label=experimental&aligned) for audioworklet and [here](https://wpt.fyi/results/content-security-policy/gen/top.meta/script-src-self/worklet-paint.https.html?label=master&label=experimental&aligned) for paintworklet.

I'll upload a PR to address this.

**Comment by evilpie** [comment]
Awesome, thank you!
