### ISSUE TITLE
Add WPT tests that test base64url characters for hashes and nonces

### ISSUE THREAD

**Issue by dveditz** [w3c/webappsec-csp#560]
The hash source allowed characters was expanded to include basee64url characters in #37, with explanatory text on how to perform hash matching in this case added later in https://github.com/w3c/webappsec-csp/commit/1ceea1b95e73d34dd717282fbe8c19189043c07b. Years later this led to a web compatibility problem in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1785871

We need platform tests that use this syntax for both nonces and hashes.

**Comment by mozfreddyb** [comment]
My Firefox patch will introduce a new test for wpt. I will land in our repo "mozilla-central" and eventually it be upstreamed through our tooling. Follow the bug if you want to know more.

**Comment by mozfreddyb** [comment]
I believe this can be closed in favor of https://github.com/web-platform-tests/wpt/pull/35601
