### ISSUE TITLE
Should we replace browsing contexts with navigables?

### ISSUE THREAD

**Issue by antosart** [w3c/webappsec-csp#579]
The spec uses browsing contexts for the frame-ancestors check. In the html spec, navigables have been introduced. Should we replace browsing contexts with navigables? If so, we should pass a navigable instead of a browsing context as target in the https://w3c.github.io/webappsec-csp/#should-block-navigation-response algorithm.

**Comment by antosart** [comment]
CC @domenic.

**Comment by domenic** [comment]
Yes, I think replacing all references to browsing contexts with the corresponding navigable terminology would be an improvement, since your spec isn't one of the few that wants to have different behaviors before and after BCG swaps.

Please let me know if I can help.
