### ISSUE TITLE
unique app id in reported violation object

### ISSUE THREAD

**Issue by telelvis** [w3c/webappsec-csp#584]
First of all, thank you for the work and effort you've put in developing this specification https://www.w3.org/TR/CSP3/#report-violation, and I apologize if it's not a right place for below question.
I'd like to check on following scenario for CSP implementation.
Let's say there is a large enterprise with many web applications hosted of various kind and purpose, looked after by different people. It would begin CSP implementation by setting up central violation report collection server and configuring app frontends to include Content-Security-Policy-Report-Only header to point to it.
To be able to digest incoming reports from user' browser and tell what violations should be worked on by what respective people, company has to have origin/domain/app inventory in a good shape. 
Let's say there is none.
Is there any way to include configurable custom identifier in violation reports, that may be assigned to the app frontend way in advance, so later we can tell the difference which violation is reported for which app.
I am looking at this schema https://www.w3.org/TR/CSP3/#violation and can't see an attribute that may be good fit for that.
Do you think this scenario makes sense and how would you solve it?
Many thanks.

**Comment by mikewest** [comment]
I'm not sure I understand the question, but there's no mechanism to add arbitrary information to the report itself, but two approaches occur to me:

1. You should receive the URL of the page on which the violation occurred. Does that give you enough information to identify which application is affected?

2. You can also vary the reporting endpoint on a page-by-page basis. One application might deliver reports to `/reporting-endpoint-1`, while another might deliver to `/reporting-endpoint-2`. You can map both URLs to your reporting application, and record things that way?

**Comment by mikewest** [comment]
👍
