### ISSUE TITLE
how do i run my computer the way i want

### ISSUE THREAD

**Issue by Vargason** [w3c/webappsec-csp#589]
I'm tried of every time I try too log in a web page it blocks it even tube;I want control of my computer how do I remove all this Security it should be up to me what I do with my Computer;I don't care if I  Mass up my Computer;I know how to rerun widows

**Comment by mikewest** [comment]
In Chrome (and other Chromium-based browsers), you can run with the `--disable-web-security` command-line flag. Perhaps other vendors have similar options?
