### ISSUE TITLE
host-part match issues

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-csp#590]
Looking at https://w3c.github.io/webappsec-csp/#host-part-match:

* Callers of this algorithm expect to be able to call it with a host, but a host is not always a string.
* It uses an RFC3986 production to determine if a string is an IPv4 address. If this is an actual primitive we need it seems this would have to be defined in the URL Standard. Perhaps there's a better way to make this requirement if one of the inputs is an actual host as defined by the URL Standard?
* It asks if a string is an IPv6 address. That will never be true.

**Comment by arichiv** [comment]
When is a host not a string? When it's an IP address? Or are there other cases?

**Comment by annevk** [comment]
Yes, when it's an IP address. That's partially why "host" is its own concept.
