### ISSUE TITLE
port-part matches issues

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-csp#591]
I had a look at https://w3c.github.io/webappsec-csp/#port-part-matches:

* A port is typically a number so comparing two strings probably doesn't work for all callers.
* The default port for a scheme is definitely a number.
* The default port can only be obtained if the scheme is a special scheme. It's UB for other schemes.
* "If _port A_ is empty" and equivalent should be written as "If _port A_ is the empty string".

**Comment by arichiv** [comment]
I think there might be another issue here, it seems like the current algorithm can't handle the case  where port a and port b are both the empty string (but the schemes match). This would handled by step 3, but ends up being caught and returning early in step 1.1 I think. @annevk am I correct or did I miss something?

**Comment by annevk** [comment]
Yeah, that's correct. Presumably this doesn't match implementations then as most of the time I would expect that to be the case.
