### ISSUE TITLE
Typo in 8.4 Allowing external JavaScript via hashes

### ISSUE THREAD

**Issue by mauke** [w3c/webappsec-csp#615]
https://github.com/w3c/webappsec-csp/blob/1fe1780b6b30a3d1fa4434750e3c1ab1ab5da6cd/index.bs#L4905 

Section 8.4 "Allowing external JavaScript via hashes" says:

> This means that it is possible for the hash needed to allow
> an inline script block to be different that the hash needed to allow an
> external script even if they have identical contents.

`different that` should be `different from`.

**Comment by antosart** [comment]
Thanks for reporting this. Fixed!
