### ISSUE TITLE
Why is the Content-Security-Policy-Report-Only header field not supported in `<meta>` elements?

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/webappsec-csp#640]
This seems to raise the burden of using Trusted Types (https://w3c.github.io/trusted-types/dist/spec/). See for instance the second use case at https://w3c.github.io/trusted-types/dist/spec/#use-cases.

CC @koto, @bkardell, @lukewarlow

**Comment by annevk** [comment]
Mutable policies are rather bad from multiple angles. The ones we have are still not defined to the level of detail needed for full interoperability. As I've argued in a lot of places, we should not proliferate them.

**Comment by mbrodesser-Igalia** [comment]
When is policy considered mutable?

**Comment by annevk** [comment]
When it can change within the lifetime of a document. E.g., from there not being a policy to there being a policy.

**Comment by gapple** [comment]
Some previous discussion is in #277

**Comment by annevk** [comment]
Thanks, let's duplicate this then.
