### ISSUE TITLE
`report-sample` is not checked when firing "securitypolicyviolation" events

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/webappsec-csp#669]
See https://w3c.github.io/webappsec-csp/#changes-from-level-2 step 11 and https://w3c.github.io/webappsec-csp/#report-violation step 3.3.

Seems an oversight?

**Comment by lukewarlow** [comment]
It seems that it should be checked when setting the violation sample value rather than when it's used?

https://w3c.github.io/webappsec-csp/#should-block-inline - for example.
