### ISSUE TITLE
How to set CSP without unsafe-inline for site with ads?

### ISSUE THREAD

**Issue by Wowhere** [w3c/webappsec-csp#686]
How to set CSP without unsafe-inline for site with ads?

Site have ads in iframe, some ads in this iframe using inline scripts. My question: How to permit inline-scripts only for this ads iframe with CSP3? Or: How to disable CSP only for ads iframe?

**Comment by mikewest** [comment]
I think you'll need to ask your ad script provider how you can best work with them to confine their scripts. I don't believe it will be possible to give a generic answer here.

**Comment by Wowhere** [comment]
Maybe there is planning for more granular settings in CSP? I cant understand how to set CSP granular for different browsing contexts

**Comment by mikewest** [comment]
I'm not sure I understand the question.

Each framed document can send its own `Content-Security-Policy` header, which applies to that document's context. The parent's policy does not need to be the same as the child's, and vice-versa. If your ad frame needs to allow inline script, it should be able to do so by simply not delivering a header which restricts it.

**Comment by Wowhere** [comment]
I`am talking about ads which embedded in DOM of original site. Example: site A (opened in tab) send XHR request and fill iframe with layout from ads site B (DOM Manipulation), so this is not iframe with src from B (iframe dont have src specified at all). Can CSP help me to define undependent politics for such iframe?

**Comment by dveditz** [comment]
If your parent context is creating the the HTML or DOM of the child then you can create a <meta> tag in the <head> of the document that specifies the content-security-policy. Do that first before adding more content.

There are a couple CSP features that will be ignored when the policy is specified in a <meta> tag. The most relevant for your use case is probably the "sandbox" directive, but you can easily put that on the <iframe> tag itself

**Comment by Wowhere** [comment]
@dveditz Sounds awesome, i will try yo test this on dev server
