### ISSUE TITLE
Add `'unsafe-dynamic'`

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-csp#70]
See discussion at https://lists.w3.org/Archives/Public/public-webappsec/2016Feb/0048.html.

We'll need to:

1. Define the new source expression.
2. Adjust HTML to pass along a script's "parser-inserted" flag's state when fetching a resource.
3. Adjust `script-src`'s {pre,post}-fetch algorithms to use the new data.

**Comment by mikewest** [comment]
@annevk: How do you feel about adding _another_ flag to requests? Maybe we should abstract this kind of thing to an "extra data" member that HTML can stuff keys and values into? I feel like CSP is adding a few requirements to Fetch that that layer shouldn't know or care about.

**Comment by annevk** [comment]
If it's just CSP I'd prefer "CSP data" with the field value defined by CSP.

**Comment by mikewest** [comment]
I was thinking about integrity metadata as well. "Stuff-relevant-to-the-element-that-triggered-this-request data"? :)

**Comment by annevk** [comment]
Integrity metadata is used directly by `new Request` though. I suppose we could refactor what it ends up setting though. Would you then also put referrer and referrer policy there?

**Comment by mikewest** [comment]
Hrm. Fair point.

I guess I'm trying to reduce the number of three-sided patches for data that really just passes through Fetch, and likewise to reduce the complexity of the HTML-side patches that are just passing information up from an element. Creating a struct of some sort would make that process simpler, but there may be other ways to simplify.

That said, if we expose the data to Fetch's APIs, then of course we need to teach Fetch about it, and that negates at least some of the value of bundling things up and defining them elsewhere.

Let me poke briefly at an HTML patch and Fetch patch to see if they make any sense. If you have suggestions in the meantime (or if you think the current layering makes sense and there's no reason to change it?), do let me know. :)

**Comment by annevk** [comment]
I don't really see a way around it, other than putting CSP and co directly in Fetch. I'm assuming the software changes are similar. If software found a way around this we could take that innovation and bring it to standards though.

**Comment by mikewest** [comment]
I'm going to give you an HTML change in a second which refactors the nonce bits and pieces to match more closely what Chrome does. We still have access to the element when we're about the kick off the request, so we can read data directly there as opposed to passing it around explicitly (see https://blink.lc/chromium/tree/third_party/WebKit/Source/core/dom/ScriptLoader.cpp#n305)

We do end up dumping a flag on the request object that turns off CSP checking entirely, which I think is the wrong thing to specify. We're going to have to change that to deal with the post-request check in CSP3, for instance.

Just adding a flag to Fetch is probably the simplest thing to do right now, though I think it's starting to get a bit ugly. As you say, though, I'm not sure I see a good way around it if we want to continue exposing things to Fetch's API (which we do).

**Comment by mikewest** [comment]
This is in, the dependencies have landed in WHATWG's HTML, and bugs are filed against W3C's HTML.
