### ISSUE TITLE
Nested browsing context navigation to non-network schemes

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#77]
I saw [this topic ](https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/sL1mPj2Y8jw), which ensured me, that [change](https://github.com/w3c/webappsec-csp/issues/69) to the spec we did is in right direction. 
However, the question prompted me to check if [sandboxed origin browsing context](https://html.spec.whatwg.org/#sandboxed-origin-browsing-context-flag)  has control over navigation to  non-[network schemes](https://url.spec.whatwg.org/#local-scheme), and I was surprised to see that there is no control over that capability. 

I think that limiting nested browsing context navigation to the defined set of schemes is in immediate CSP interest, or perhaps fetch? Can we do something in CSPland to have that capability?

**Comment by mikewest** [comment]
I don't really understand what you're asking for. Could you be a little more concrete with your suggestion?

**Comment by shekyan** [comment]
I ask if requiring parent context to opt-in to allow navigating iframes to non-network schemes is sane idea or not (if it both fits CSP roadmap and is technically possible to implement by browsers without rewriting everything).

**Comment by mikewest** [comment]
Duping this into https://github.com/w3c/webappsec-csp/issues/125.
