### ISSUE TITLE
Inline scripting violation: add a script-sample property to the report payload

### ISSUE THREAD

**Issue by romainneutron** [w3c/webappsec-csp#81]
Hello,

Firefox provides a `script-sample` property in a directive violation report regarding an inline script. It's pretty useful to detect false positive when collecting data with a `report-uri`.

It seems the idea had been proposed few years ago (see https://www.w3.org/Security/wiki/Content_Security_Policy#Proposals_for_Version_1.1), and as a user I get a very large benefit of getting this property when gathering reports from Firefox.

Unfortunately Chrome and other browsers do not implement this feature.

Adding this payload property (in case the violation is an inline scripting violation) to the spec in version 3 would be very useful to help people diagnosing their report and therefore encourage them to deploy CSPs on their web apps.

**Comment by mikewest** [comment]
Folding this into #119.
