### ISSUE TITLE
path-part should be represented by path-abempty

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#89]
I hit this issue again, and realized we [reported it](https://github.com/w3c/webappsec/issues/361) a while back, and it wasn't ported to the new repo.

In [Source Lists](https://w3c.github.io/webappsec-csp/#framework-directive-source-list) section, `path-part` should be production of `path-abempty`, rather than `path` of [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.3).

**Comment by shekyan** [comment]
Copied from original issue: w3c/webappsec#501

**Comment by shekyan** [comment]
Also, `path` being production of `path-empty` makes every source-expression to contain path-part, empty or not.

**Comment by annevk** [comment]
Has anyone looked into how these productions are implemented in practice? Do user agents simply reuse their URL parsers? E.g., https://url.spec.whatwg.org/?

**Comment by mikewest** [comment]
Chrome does not. See https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/frame/csp/CSPSourceList.cpp&sq=package:chromium&l=151&rcl=1463743191 for the gory detail. If we ever decide it's worthwhile to change CSP's syntax in some way, ripping all of this out in favor of a reasonable parser is right at the top of my list.
