### ISSUE TITLE
Clarify the target for `SecurityPolicyViolationEvent`

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#90]
Current spec implies that target for `SecurityPolicyViolationEvent` is the [global object](http://www.w3.org/TR/html5/webappapis.html#global-object). It should be Document if in document, or WorkerGlobalScope if inside the worker.

**Comment by shekyan** [comment]
@mikewest , would changing "`{{Window}}`" to "`{{Document}}`" [here](https://github.com/w3c/webappsec-csp/blob/master/index.src.html#L433) do it?

**Comment by mikewest** [comment]
I'd suggest changing step 1 of section 5.3 to something like "Fire a trusted event with the name `securitypolicyviolation` at |violation|'s global object if it is a WorkerGlobalScope, or at |violation|'s global object's document otherwise. The event must use the SecurityPolicyViolationEvent interface, with its attributes initialized as follows:".

**Comment by annevk** [comment]
You probably want "relevant global object" assuming _violation_ is a platform object. And for that global object's `Document` object you want https://html.spec.whatwg.org/#concept-document-window.

**Comment by mikewest** [comment]
I think we want https://w3c.github.io/webappsec-csp/#violation-global-object for "global object". It looks like the settings object definition has changed, though, which means that step 1 of https://w3c.github.io/webappsec-csp/#create-violation-for-request is no longer a thing that exists. I guess I need to reference https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-global there?

**Comment by annevk** [comment]
I don't think concept-request-global-object ever existed in Fetch? And yeah, that seems right.

**Comment by mikewest** [comment]
Yeah. I don't know where I came up with that link. Clearly wrong. Addressed in https://github.com/w3c/webappsec-csp/commit/7c3d2acf813ed2400532a51ac9dba69c5d77b07c.
