### ISSUE TITLE
Add "disposition" attribute to SecurityPolicyViolationEvent

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec-csp#94]
There is no direct way to programmatically tell if violated policy is enforced or report-only. 
Expose [disposition](https://w3c.github.io/webappsec-csp/#policy-disposition) of violated policy to the `SecurityPolicyViolationEvent`, with a value equal to "report" or "enforce".

**Comment by mikewest** [comment]
Closed in https://github.com/w3c/webappsec-csp/commit/4b6de3001598e7317de5ceea41c7bd861f0bf753.
